### PR TITLE
Add missing declaration for react-redux

### PR DESCRIPTION
**Pull request by alexkuz**

### CODE REVIEW

**Comment by marudor** [comment]
Could you please include a test case for this declaration?

**Comment by sibelius** [comment]
is this still relevant?

**Comment by marudor** [comment]
Please reopen if this is still relevant.

**Comment by alexkuz** [comment]
I think it was covered with this one: https://github.com/flowtype/flow-typed/commit/ab8db5f14de2c38de70c149d0079b5d4b70f86a3 so it's ok to close it, thank you :)

**Pull request closed without merging**
