### PR TITLE
Add initial formik types 

### PR DESCRIPTION
**Pull request by aaronjensen**
Still a work in progress, but can be merged as a start. Any help is appreciated. Thanks!

https://github.com/jaredpalmer/formik/issues/78

### CODE REVIEW

**Comment by sibelius** [comment]
I think we can merge this half-baked and then improve it later on

what do u guys think?

**Comment by aaronjensen** [comment]
@sibelius I'd be down, but we should probably type the HOC as Function

**Comment by aaronjensen** [comment]
Ok, this should be ready to merge now. /cc @GAntoine

**Comment by aaronjensen** [comment]
@GAntoine Sure, done.

**Comment by ZwaarContrast** [comment]
I'm having issues using types of formik.
I get these errors:
```
[flow] property `dirty` is not readable.
[flow] property `initialValues` is not readable.
[flow] property `isValid` is not readable.
```
With this code:
```
<Formik
            initialValues={{ comments: '' }}
            onSubmit={values => {
                console.log('Submit', values)
            }}
            render={(props: FormikProps<Values>) => (
                <RequestForm  {...props} />
            )}
        />

type Values = {
    comments: string,
}
```

Am i doing something wrong?

**Comment by aaronjensen** [comment]
@ZwaarContrast I think I reversed the read-only/write-only. If you change the `-` to a `+` in `FormikComputedProps`, does it fix your problem? If so, could you PR that along w/ your test case? Thanks!

**Pull request merged**
