### PR TITLE
[react-relay] Replace FlowFixMe with *

### PR DESCRIPTION
**Pull request by vnctaing**
That should fix that error  

screen shot 2018-01-25 at 11 41 28 am

### CODE REVIEW

**Comment by GAntoine** [comment]
Is `*` the right type thing to use here?

**Comment by vnctaing** [comment]
I'm not totally sure, but I don't think Flow is able to determine the variables type in advance to the `RelayRuntime` package. 

I think the original flow-typed definition was coming from that [commit](https://github.com/facebook/relay/commit/0a4027d4c2328549e2d314dbb5eb8ad1eeaeb051#diff-acbf22bc09d64e2ad9b25c12298f9859R30)

I've tried to analogically look into [how they check the graphql variables](https://github.com/apollographql/react-apollo/blob/76fc936f6292ef214a6eeb6cfd9963d573b871d8/src/types.ts#L15) typing in react-apollo. 

```
export type OperationVariables = {
  [key: string]: any; // I try to avoid using `any` in favor of `*`
};
```
Maybe input from someone more familiar with relay codebase would be more than welcome ?

**Comment by GAntoine** [comment]
@sibelius Could I get your input on this?

**Comment by sibelius** [comment]
I think variables can have any kind of value, or maybe only primitives types

**Comment by vnctaing** [comment]
You're right, we shouldn't let pass functions or class through variables. I guess an union type of primitive would work. like `boolean | string | number | null | void`

**Comment by vnctaing** [comment]
Actually we want to be able to send plain object to the union type too. I've forgotten to add it to the union type... opening a PR ...

**Pull request merged**
