### PR TITLE
Firebase v5 definitions

### PR DESCRIPTION
**Pull request by meafmira**

### CODE REVIEW

**Comment by wcandillon** [comment]
@meafmira Thanks for contributing this. Out of curiosity, was this type definition build manually or was it generated from somewhere?

I did notice that `currentUser` should be:
-  currentUser: $npm$firebase$auth$User | null;

**Comment by wcandillon** [comment]
Also onSnapshot should allow async callbacks (that return a promise). 
=> void
should become
=> void | Promise<void>

This is true in a lot of places where a callback is allowed as a parameter.

**Comment by meafmira** [comment]
@wcandillon It's based on firebase_v4 but with some fixes. For example changed 'firebase/app' exports. I'll fix callbacks

**Comment by wcandillon** [comment]
yes thanks for fixing the /app export :)

**Comment by meafmira** [comment]
@wcandillon are you sure about `onSnapshot` signature? I checked this https://firebase.google.com/docs/reference/js/firebase.firestore.Query#onSnapshot and see it should return unsubscribe function not a Promise

**Comment by meafmira** [comment]
@wcandillon Updated `onSnapshot` and `currentUser` signatures

**Comment by wcandillon** [comment]
Yes because the user might use `await` in his callback.

Thanks a lot for the changes, you are the man 🙌🏻

**Comment by meafmira** [comment]
@wcandillon Oh I didn't understand what do you mean at first.
I've updated onSnapshot callbacks signatures and fixed all tests

**Comment by wcandillon** [comment]
@meafmira Thank you for your work. I just reviewed and tested this type definition in my project and it works for me 👍🏻

**Comment by GAntoine** [comment]
LGTM based on @wcandillon approval 👍

**Pull request merged**
