### PR TITLE
#275: adding support for react-router

### PR DESCRIPTION
**Pull request by kayneb**
This PR adds support for react-router to definitions. This is my first time writing type definitions, so please forgive me if I've missed anything.

### CODE REVIEW

**Comment by elliottsj** [comment]
Thanks, I've been looking for some react-router Flow types 😄 

I wonder if it's also worth creating separate definitions for [history](https://github.com/mjackson/history), like how the [TypeScript definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/084e55916674ff7128722bf72150aa55acea08d9/react-router/react-router.d.ts#L8) depend on [types from history](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/084e55916674ff7128722bf72150aa55acea08d9/history/history.d.ts). Then we can have more complete types for things like `router.push(location)`.

I'll look into creating some definitions for history.

Though unfortunately, until https://github.com/flowtype/flow-typed/issues/16 is resolved, I don't think there's a way to use history types in the react-router libdef, since flow-typed tests libdefs in isolation 😞

**Comment by thejameskyle** [comment]
Can you specify the `Object`s, `Function`s, and `any`s more?

**Comment by runn1ng** [comment]
Nice, thanks  @kayneb

**Comment by marudor** [comment]
This hasn't been updated for quite a while and I can't add commits to the PR.
If this is still relevant please submit a new PR.

**Comment by omrihq** [comment]
Is there any update on a flowtype for `history`?

**Comment by keithkml** [comment]
This appears to be the only definition of types for react-router v2. Why was this abandoned?

**Comment by CoenWarmer** [comment]
I'd also like to +1 flowtype support for `history`

**Comment by mvanlonden** [comment]
`History` is typed through the `history` npm module. Flow-typed has a definition for this module

**Pull request closed without merging**
