### PR TITLE
Add typing for return type of underscore's _.times

### PR DESCRIPTION
**Pull request by jetpacmonkey**
There was a definition for `_.times`, but it didn't account for the fact that it can be used to build up an array with the return values of the iteratee. I tried to imitate the surrounding code style as much as possible, happy to make any additional changes as needed!

### CODE REVIEW

**Comment by jetpacmonkey** [comment]
It looks like some definitions I didn't touch are causing the build to fail?

**Comment by GAntoine** [comment]
@jetpacmonkey Looking at the logs, the specs are indeed failing on your changes to underscore: `ERROR: underscore_v1.x.x/flow_v0.50.x-`

**Comment by jetpacmonkey** [comment]
Hmm, that is the file that I changed, but the actual failures look like they're unrelated to my changes. I just ran the tests locally on master, and saw the same errors.

**Comment by GAntoine** [comment]
Yeah looks like the current definition is broken for some of the newer flow versions.

**Comment by jetpacmonkey** [comment]
So what's the path forward, then?

**Comment by GAntoine** [comment]
I'll merge it in, even though it's failing, since the changes do look ok.

**Pull request merged**
