### PR TITLE
bootstrap-datepicker

### PR DESCRIPTION
**Pull request by gregegan**
https://www.npmjs.com/package/bootstrap-datepicker

### CODE REVIEW

**Comment by marudor** [comment]
Just like your other PRs - could you fix the names?

**Comment by thejameskyle** [comment]
Yup the two files you should have are these:

```
/bootstrap-datepicker_v1.x.x/flow_>=v0.30.x/bootstrap-datepicker_v1.x.x.js.flow
/bootstrap-datepicker_v1.x.x/test_bootstrap-datepicker_v1.x.x.js.flow
```

The second is for adding tests to have a sanity check.

**Comment by gregegan** [comment]
fixed file names

**Comment by marudor** [comment]
This hasn't been updated for quite a while and I can't add commits to the PR.
If this is still relevant please submit a new PR.

**Pull request closed without merging**
