### PR TITLE
Add libdef for lockfile v0.1.x for flow >= 0.47.x

### PR DESCRIPTION
**Pull request by juanpicado**
Add type definitions for `lockfile`. 

https://www.npmjs.com/package/lockfile

### CODE REVIEW

**Comment by juanpicado** [comment]
The tests are failing, it seems an external factor 🤔, not related to my changes.

**Comment by GAntoine** [comment]
Any reason you stopped at flow version 54? If the specs run on 55+, you can change the folder name to `flow_v0.47.x-`.

**Comment by juanpicado** [comment]
Ok, my bad :) first time contributing here. I'll fix it.

**Comment by GAntoine** [comment]
No worries! Everything looks good, thanks for contributing 💪

**Pull request merged**
