### PR TITLE
Update react-navigation libdef

### PR DESCRIPTION
**Pull request by Ashoat**
We maintain our libdef in our [repo](https://github.com/react-navigation/react-navigation/blob/master/flow/react-navigation.js), and we make updates to it there. This PR merges our version upstream.

This PR also introduces a `CONTRIBUTING.md` in the `react-navigation` folder with more info about our process.

### CODE REVIEW

**Comment by AndrewSouthpaw** [comment]
I merged a PR that will allow this one to be possible. Please rebase and see if the tests run successfully now.

**Comment by Ashoat** [comment]
Hey sorry about that, I lost track of this PR for some reason. Rebased and the checks are passing.

**Comment by Ashoat** [comment]
Ping!

**Comment by AndrewSouthpaw** [comment]
Thanks for the ping! I'm nearly done with the backlog. 😅

**Pull request merged**
