### PR TITLE
Do not fail on 'Invalid comparator' error

### LINKED ISSUE #399: UNCAUGHT ERROR: TypeError: Invalid comparator: latest
When trying to do "flow-typed install", it fails, error follows:

> c:\dev\project1>flow-typed install
> UNCAUGHT ERROR: TypeError: Invalid comparator: latest
>     at Comparator.parse (C:\Program Files (x86)\Nodist\bin\node_modules\flow-typed\node_modules\semver\semver.js:678:11)
>     at new Comparator (C:\Program Files (x86)\Nodist\bin\node_modules\flow-typed\node_modules\semver\semver.js:662:8)
>     at C:\Program Files (x86)\Nodist\bin\node_modules\flow-typed\node_modules\semver\semver.js:780:12
>     at Array.map (native)
>     at Range.parseRange (C:\Program Files (x86)\Nodist\bin\node_modules\flow-typed\node_modules\semver\semver.js:779:13)
>     at Range.<anonymous> (C:\Program Files (x86)\Nodist\bin\node_modules\flow-typed\node_modules\semver\semver.js:721:17)
>     at Array.map (native)
>     at new Range (C:\Program Files (x86)\Nodist\bin\node_modules\flow-typed\node_modules\semver\semver.js:720:40)
>     at determineFlowVersion$ (C:\Program Files (x86)\Nodist\bin\node_modules\flow-typed\dist\lib\npmProjectUtils.js:195:26)
>     at tryCatch (C:\Program Files (x86)\Nodist\bin\node_modules\flow-typed\node_modules\regenerator-runtime\runtime.js:62:40)

What causes this error?

### LINKED ISSUE #1127: [Feature] Ignore non semver versions on install
#895 and #1124 are related.
It would be nice if we do not throw an error but ignore non semver versions and emit a warning at the end.
That way the User can install libdefs manually.

PR for this very welcomed!

### PR DESCRIPTION
**Pull request by cema-sp**
Trying to install definitions with `flow-typed install` I faced an `Invalid comparator` error due to GitHub repo dependency in my _package.json_ file.

This solution avoids `Invalid comparator` errors by ignoring non-semver packages and and installing stubs for them.

Closes #1127

### CODE REVIEW

**Comment by vinnymac** [comment]
@cema-sp to get this to work for me I had to modify `npmLibDefs.js` [here](https://github.com/flowtype/flow-typed/blob/master/cli/src/lib/npm/npmLibDefs.js#L336) with the below snippet. Not sure why I needed this in addition to your changes.

```
if (filter.pkgName.toLowerCase() === def.name.toLowerCase()) {
          try {
            filterMatch = pkgVersionMatch(filter.pkgVersion, def.version);
          } catch(error) {
            if (error.message.indexOf('Invalid comparator') > -1) {
              console.error(
                `\u2022 Unprocessible version of '${filter.pkgName}' ` +
                `in package.json: '${filter.pkgVersion}'.`
              );
            } else {
              throw error;
            }
          }
        }
```

**Comment by IanVS** [comment]
Hi there, I have been manually removing the github repos in my `package.json` whenever I need to `flow-typed install`, which is a bit of a pain.  This is a fairly significant bug in my mind, and it would be awesome to get this merged and released.  Looks like it's been sitting for a while. @cema-sp will you be updating this to incorporate @vinnymac's patch?  If not, I can copy this work and create another PR, because I'd really love to get this fixed.

**Comment by vinnymac** [comment]
@IanVS I would like to see these changes get merged in as well. I actually don't use `flow` at all right now, waiting till bugs such as this get fixed. If their is anything I can do to help, let me know.

**Comment by GAntoine** [comment]
@cema-sp There's a new feature issue at #1127 for this exact bug, and a number of other ones. If you can rebase this we can probably get it merged.

**Comment by cema-sp** [comment]
Apologize for such a delay.
I found a better and more straightforward solution, please review it.
PR is already rebased.

Resolves #1127

**Comment by GAntoine** [comment]
I appreciate your patience, thanks again for the fix 💪

**Pull request merged**
