### PR TITLE
Add forward-looking rxjs test

### PR DESCRIPTION
**Pull request by nmote**
Details in the comment

### CODE REVIEW

**Comment by marudor** [comment]
Well.. now that we have a PR for covariatns this should be unneccesary?

**Comment by nmote** [comment]
We should still have this test

**Comment by nmote** [comment]
I'll spend some time today sorting out all the rxjs libdef PRs. I've been given push access to this repository so hopefully I'll be able to help out here and there.

**Comment by nmote** [comment]
I'm going to wait for #446 to land, then I'll add this test.

**Comment by nmote** [comment]
Looks like @hansonw folded this in here: https://github.com/flowtype/flow-typed/pull/446/files#diff-a738673b9a709d40b8498e5361acc877

**Pull request closed without merging**
