### PR TITLE
make the rxjs libdefs compatible with 0.33.0

### PR DESCRIPTION
**Pull request by Kriegslustig**

### CODE REVIEW

**Comment by inlinestyle** [comment]
Hey thanks for this! Also it looks like this fixes the FIXME comment on line 13.

**Comment by Kriegslustig** [comment]
Oh right. Thanks! I removed it.

**Comment by inlinestyle** [comment]
I'd love for this to get merged, as it will make it easier to upgrade to Flow 0.33.0 (though in the worst case I'll source this forked version).
I'm also wondering if it's necessary to cap the libdef at Flow 0.33.0, as opposed to assuming it will be compatible with Flow >= 0.34.0. It seems like most of the other libdefs are forward-compatible until proven otherwise (and this is in keeping with the [contributing guidelines](https://github.com/flowtype/flow-typed/blob/master/CONTRIBUTING.md#2-in-this-new-directory-create-another-new-directory-called-flow_all)).

**Comment by Kriegslustig** [comment]
Oh right will fix that right away. Thanks!

**Comment by inlinestyle** [comment]
@Kriegslustig thanks! Though I'm not a maintainer, so it's just my opinion not repo policy :)

**Comment by Kriegslustig** [comment]
@inlinestyle if you wanted to add something to the rxjs libdefs you might want to look at [the branch I'm working on](https://github.com/kriegslustig/flow-typed/tree/definition/rxjs-extended). I have actually implemented most missing operators and am mainly waiting for this to get merged before submitting another pull request.

**Comment by inlinestyle** [comment]
@Kriegslustig yeah I filed https://github.com/flowtype/flow-typed/pull/327; I don't see the operators it adds in your branch (`let`, `letBind`, `switch`), but I'd be happy to file a PR to your branch if you want.

**Comment by Kriegslustig** [comment]
@inlinestyle That'd be great! But it would probably be best if you submit the PR to `flowtype/flow-typed` directly. The branches will likely be easy to merge.

**Comment by inlinestyle** [comment]
@marudor (and other maintainers) sorry to bother you here too, do think this is mergeable?

**Comment by marudor** [comment]
merged with commit 5459d1a

**Pull request closed without merging**
