### PR TITLE
add jest-cli to dev dependencies, fix #1066

### LINKED ISSUE #1066: cannot find module jest-cli on cli tool
Error: Cannot find module '/Users/sibelius/Dev/me/flow-typed/cli/node_modules/jest-cli'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at getJest (/Users/sibelius/Dev/me/flow-typed/cli/node_modules/jest/node_modules/jest-cli/build/cli/getJest.js:22:12)
    at Object.run (/Users/sibelius/Dev/me/flow-typed/cli/node_modules/jest/node_modules/jest-cli/build/cli/index.js:39:48)
    at Object.<anonymous> (/Users/sibelius/Dev/me/flow-typed/cli/node_modules/jest/node_modules/jest-cli/bin/jest.js:14:25)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)

### PR DESCRIPTION
**Pull request by sibelius**

### CODE REVIEW

**Comment by GAntoine** [comment]
I'd assume `jest-cli` would be installed automatically, seeing as it's listed as a dependency of `jest` on npm. So I don't think adding it manually to the `devDependencies` is necessary.

**Comment by sibelius** [comment]
I've installed using `yarn`, and it did not worked well

**Comment by GAntoine** [comment]
Try `rm -rf node_modules` from within the `flow-typed/cli` folder, and `yarn install` again. I just did it and it installed everything correctly. Maybe try updating your local version of yarn as well?

**Comment by sibelius** [comment]
tried again did not worked

**Pull request closed without merging**
