### PR TITLE
Copy typedefs from knex_v0.12.x to knex_v0.13.x

### PR DESCRIPTION
**Pull request by eqyiel**
This is another one of these: https://github.com/flowtype/flow-typed/issues/374

Unfortunately it seems that package version directories cannot contain a semver range, so I've resubmitted the existing v0.12.x definitions.

### CODE REVIEW

**Comment by eqyiel** [comment]
I don't really know what to make of these errors, the tests pass when I run them locally: https://gist.github.com/eqyiel/bd285122f48e665a5e7769b6547b6928

**Comment by GAntoine** [comment]
I took a diff of this version and the latest version of knex 12, could it be related to the changes below?

```diff
--- a/definitions/npm/knex_v0.12.x/flow_v0.38.x-/knex_v0.12.x.js
+++ b/definitions/npm/knex_v0.12.x/flow_v0.38.x-/knex_v0.12.x.js
@@ -1,4 +1,4 @@
-declare class Knex$Transaction<R> mixins Knex$QueryBuilder<R>, events$EventEmitter, Promise<R> {
+declare class Knex$Transaction<R> {
   commit(connection?: any, value?: any): Promise<R>,
   rollback(): Promise<R>,
   savepoint(connection?: any): Promise<R>
@@ -8,7 +8,7 @@ declare type Knex$QueryBuilderFn<R> = (
   qb: Knex$QueryBuilder<R>
 ) => Knex$QueryBuilder<R> | void;

-declare class Knex$QueryBuilder<R> mixins Promise<R> {
+declare class Knex$QueryBuilder<R> {
   select(key?: string[]): this,
   select(...key: string[]): this,
   timeout(ms: number, options?: { cancel: boolean }): this,
@@ -129,7 +129,7 @@ declare class Knex$QueryBuilder<R> mixins Promise<R> {
   returning(columns: string[]): this
 }

-declare class Knex$Knex<R> mixins Knex$QueryBuilder<R>, Promise<R>, events$EventEmitter {
+declare class Knex$Knex<R> {
   static (config: Knex$Config): Knex$Knex<R>,
   static QueryBuilder: typeof Knex$QueryBuilder,
   $call: (tableName: string) => Knex$QueryBuilder<R>,
```

**Comment by eqyiel** [comment]
I don't know why it would be failing because of that given that the tests are the same, but if you know something I don't please let me know!

**Comment by GAntoine** [comment]
Are the specs failing locally? My guess (and this is 100% a guess) would be that, since you're no longer `mixin` `Knex$QueryBuilder<R>` with `Knex$Knex<R>`, your exported type (L99) no longer contains the methods you need it to.

**Comment by eqyiel** [comment]
@GAntoine thanks for clearing that up, I thought you were saying that those mixins existed in an older version of the knex_v0.12.x definition!

**Comment by eqyiel** [comment]
@GAntoine it looks like the pre-commit hook was nuking those mixins for some reason.  This must have been why the tests passed before I made a commit!

**Comment by GAntoine** [comment]
Thanks for the 🔥 libdef update.

**Comment by eqyiel** [comment]
Thanks!

**Pull request merged**
