### PR TITLE
Add type definitions for bluebird-promisell

### PR DESCRIPTION
**Pull request by zhangchiqing**
I'm adding type definitions to my library [bluebird-promisell](https://github.com/zhangchiqing/bluebird-promisell).

When I ran `./run_def_tests.sh bluebird-promisell`, I got the following error. How can I resolve the first error, which is saying `bluebird` not found? (My library depends on `bluebird`, so does the tests).

```
 * bluebird-promisell_v0.5.x/flow_>=v0.29.x (flow-v0.33.0): Unexpected Flow errors(2):
   0-test_bluebird-promisell_v0.5.x.js:3
     3: import type { Bluebird$Promise } from 'bluebird';
                                              ^^^^^^^^^^ bluebird. Required module not found

   0-test_bluebird-promisell_v0.5.x.js:11
    11: // $ExpectError
        ^^^^^^^^^^^^^^^ Error suppressing comment. Unused suppression
...

   Found 14 errors

   null
```

Thanks!

### CODE REVIEW

**Comment by zhangchiqing** [comment]
I figured a workaround is to [export the Bluebird promise type in the library](https://github.com/flowtype/flow-typed/pull/410/commits/1252d021125610e0741962c2d5a7f509d8b6b931#diff-e03885c133a1b3981b48ae3cdf291ee3R5).

Not sure if there is better way to do it. 

The CI is returning green light. I think It's ready for review :)

Could anyone review my PR?

**Comment by zhangchiqing** [comment]
Hi @jeffmo, could you kindly review my PR? Thanks!

**Comment by marudor** [comment]
Just looking at the typings it looks good.
I'm not sure about the import from bluebird though..

Second Opinions?
@jeffmo @ryyppy

**Comment by ryyppy** [comment]
I disconnected from the flow development lately... is it possible to already do imports in libdefs? That would be neat-o.

**Comment by ryyppy** [comment]
@marudor I wonder how the CI lets this thing through? Is it even aware of the `bluebird` dependency or does it just assume it to be `any`?

**Pull request merged**
