### PR TITLE
Add applyTo to Ramda

### PR DESCRIPTION
**Pull request by bigslycat**
Support for [applyTo](http://ramdajs.com/docs/#applyTo)

```js
var t42 = R.applyTo(42);
t42(R.identity); //=> 42
t42(R.add(1)); //=> 43
```

### CODE REVIEW

**Comment by AndrewSouthpaw** [comment]
Needs tests. :)

**Comment by bigslycat** [comment]
@AndrewSouthpaw done. But tests fails anyway. This was broken before my changes.

**Comment by AndrewSouthpaw** [comment]
Noted, I'll look into fixing the build.

**Comment by AndrewSouthpaw** [comment]
This needs to be rebased before we can move forward.

**Comment by bigslycat** [comment]
Done.

**Comment by AndrewSouthpaw** [comment]
Looks like there are still some errors that will need to be addressed before it can be merged.

**Comment by bigslycat** [comment]
My changes were simply copied. I'm at a loss.

**Comment by AndrewSouthpaw** [comment]
@bigslycat It looks like it's just an issue with duplicated variable names using `const`. It should be easy to fix. :)

**Comment by GAntoine** [comment]
Closed in favour of #2093

**Pull request closed without merging**
