### PR TITLE
Update styled-components for flow v0.75.0

### PR DESCRIPTION
**Pull request by dashed**
Closes https://github.com/flowtype/flow-typed/issues/2406

### CODE REVIEW

**Comment by dashed** [comment]
https://travis-ci.org/flowtype/flow-typed/jobs/396012984

Unsure why this is segfaulting:

```
ERROR: styled-components_v2.x.x/flow_v0.53.x-v0.74.x
 * styled-components_v2.x.x/flow_v0.53.x-v0.74.x (flow-v0.63.0): Unexpected Flow errors(139):
   Segmentation fault
   
   null
ERROR: styled-components_v3.x.x/flow_v0.57.x-v0.74.x
 * styled-components_v3.x.x/flow_v0.57.x-v0.74.x (flow-v0.63.0): Unexpected Flow errors(139):
   Segmentation fault
   
   null
```

Running `./run_def_tests.sh styled-components` passes on my local machine (Macbook Pro).

**Comment by breadadams** [comment]
Hey @dashed, you'll probably want to include `SafeAreaView` (#2404) in your Native definitions

**Comment by dashed** [comment]
@GAntoine I've rebased against `master` and it still seem to segfault 😕 https://travis-ci.org/flowtype/flow-typed/jobs/396934176

**Comment by GAntoine** [comment]
You can ignore the segfault now that it's rebased. Are you planning on including `SafeAreaView` as breadadams mentioned?

**Comment by dashed** [comment]
@GAntoine @breadadams I've added `SafeAreaView` 👍

**Pull request merged**
