### PR TITLE
Add assert.throws to chai definitions

### PR DESCRIPTION
**Pull request by kalman**
See http://chaijs.com/api/assert/#method_throws.

### CODE REVIEW

**Comment by kalman** [comment]
Also have a look at https://github.com/chaijs/chai/blob/master/lib/chai/core/assertions.js#L1626

**Comment by kalman** [comment]
Come to think of it, this should match `ExpectChain.throw`, but the definition for `throw` is wrong. Give me a moment and I'll fix both.

**Comment by jonfreedman** [comment]
What about doesNotThrow as well?

**Comment by kalman** [comment]
Right - it's documented there, but I actually don't see it in the chai source code - https://github.com/chaijs/chai/blob/master/lib/chai/core/assertions.js. Am I missing something?

**Comment by kalman** [comment]
And never mind, I found it in a different file. https://github.com/chaijs/chai/blob/master/lib/chai/interface/assert.js#L1788

**Pull request merged**
