### PR TITLE
Add recompose definitions

### PR DESCRIPTION
**Pull request by istarkov**
definitions for [recompose](https://github.com/acdlite/recompose)

PS:
travis check seems like broken as error I see have nothing with this PR

### CODE REVIEW

**Comment by idris** [comment]
Whats the purpose of this if you're adding the types directly to the recompose library?

**Comment by istarkov** [comment]
What are you mean? Based on docs the only way I see is to add library definitions here.
For now recompose contains libdefs only, and does not uses flow inside.

**Comment by idris** [comment]
Ah okay

**Comment by InvictusMB** [comment]
I get the following error after this PR using `flow-typed@2.1.2`:
```
• Found 84 dependencies in package.json to install libdefs for. Searching...
• rebasing flow-typed cache...
UNCAUGHT ERROR: TypeError: Invalid comparator: ^v0.24.x-
    at Comparator.parse (/Users/x088618/Projects/afkl-onboard-portal/node_modules/semver/semver.js:678:11)
    at new Comparator (/Users/x088618/Projects/afkl-onboard-portal/node_modules/semver/semver.js:662:8)
    at /Users/x088618/Projects/afkl-onboard-portal/node_modules/semver/semver.js:780:12
    at Array.map (native)
    at Range.parseRange (/Users/x088618/Projects/afkl-onboard-portal/node_modules/semver/semver.js:779:13)
    at Range.<anonymous> (/Users/x088618/Projects/afkl-onboard-portal/node_modules/semver/semver.js:721:17)
    at Array.map (native)
    at new Range (/Users/x088618/Projects/afkl-onboard-portal/node_modules/semver/semver.js:720:40)
    at pkgVersionMatch (/Users/x088618/Projects/afkl-onboard-portal/node_modules/flow-typed/dist/lib/npm/npmLibDefs.js:309:21)
    at /Users/x088618/Projects/afkl-onboard-portal/node_modules/flow-typed/dist/lib/npm/npmLibDefs.js:333:82

```
This happens if recompose version is written with caret in package dependencies.
```
"recompose": "^0.24.0"
```
However it does not happen with exact version dependency.
```
"recompose": "0.24.0"
```
Might be related to #983 topic

**Comment by marudor** [comment]
I just tried it myself. A project with just recompose in the package.json and flow-typed install - works
Could you do flow-typed update-cache and try again?

**Comment by InvictusMB** [comment]
@marudor I have deleted my comment as by the time I sent it #1034 and #1035 were created and fixed stuff.

**Pull request merged**
