### PR TITLE
Allow CONTRIBUTING.md files in libdefs.

### LINKED ISSUE #1926: Allow CONTRIBUTING.md file in sub folders
Related to [this discussion](https://github.com/flowtype/flow-typed/commit/6475dcc6d17d87bf2bebb027320cdc404dfb39d3#comments) and [here](https://github.com/flowtype/flow-typed/issues/1915), we're going to add a `CONTRIBUTING.md` file. But right now tests fail when that happens, see #1925 and its [failing build](https://travis-ci.org/flowtype/flow-typed/jobs/350403286):

```
react-navigation_v1.x.x/CONTRIBUTING.md:
  • Unexpected file name. This directory can only contain test files or a libdef file named `react-navigation_v1.x.x.js`.
```

That needs to be fixed before #1925 can be merged.

### PR DESCRIPTION
**Pull request by AndrewSouthpaw**
Closes #1926, allows #1925 to work.

### CODE REVIEW

**Comment by AndrewSouthpaw** [comment]
The build failing is due to an unrelated error.

**Comment by ahutchings** [comment]
This is causing an error when updating flow libdefs using the flow-typed cli tool. Looks like we need to either release a flow-typed cli tool update with CONTRIBUTING.md support, or revert the addition of CONTRIBUTING.md inside the ramda directory -

```bash
❯ npx flow-typed update
npx: installed 146 in 5.698s
• Found 54 dependencies in package.json to install libdefs for. Searching...
• rebasing flow-typed cache...
UNCAUGHT ERROR: Error: ramda_v0.x.x/CONTRIBUTING.md: Unexpected file name. This directory can only contain test files or a libdef file named `ramda_v0.x.x.js`.
```

**Comment by shoota** [comment]
i got same error with `flow-typed install -s`.

**Comment by CesarLanderos** [comment]
me too 😭

**Comment by AndrewSouthpaw** [comment]
argh

Reverting, and I'll talk with @GAntoine about doing a new release. Sorry everyone.

**Pull request merged**
