### PR TITLE
Bluebird.join: allow handler to return Promisable.

### PR DESCRIPTION
**Pull request by StreetStrider**

### CODE REVIEW

**Comment by StreetStrider** [comment]
Job failed, but errors come from other defs on `master`.

**Comment by StreetStrider** [comment]
@marudor, can you please review this? I see tests falling, but this mostly to be the fault of other edits on `master`. I can rebase, if required, but branch seemes OK-mergeable.

**Comment by StreetStrider** [comment]
@nmote

**Comment by nmote** [comment]
seems legit

**Comment by StreetStrider** [comment]
Great. Thank you.

**Pull request merged**
