### PR TITLE
WIP: react-redux

### PR DESCRIPTION
**Pull request by bsr203**
my attempt to start with `react-redux` typing met with error. Please help.

```
ERROR: react-redux_v4.4.0--flow_>=v0.24.2
 * react-redux_v4.4.0--flow_>=v0.24.2 (flow-v0.24.2): Unexpected Flow errors(2):
   0-test_react-redux-v4.4.0.js:2
     2: import { connect, Provider } from 'react-redux';
                          ^^^^^^^^ class type: Provider. This type is incompatible with
   union: type application of polymorphic type: type `ReactClass` | key set. See lib: react.js:174
     Member 1:
     type application of polymorphic type: type `ReactClass`. See lib: react.js:174
     Error:
      21:     props: Props;
                     ^^^^^ property `children`. Property not found in. See lib: react-redux_v4.4.0.js:21
       4: const A = <Provider />;
                    ^^^^^^^^^^^^ props of React element `Provider`
     Member 2:
     key set. See lib: react.js:174
     Error:
       2: import { connect, Provider } from 'react-redux';
                            ^^^^^^^^ class type: Provider. This type is incompatible with
     key set. See lib: react.js:174


   Found 1 error

   null
```

### CODE REVIEW

**Comment by nmn** [comment]
Needs more work IMO. The connect function is probably better off written like this:

```js
declare function connect<Config, S: Object, A: Object, SP: Object, DP: Object, Store: Object>(
  mapStateToProps: (store: S, props: $Diff<Config, SP&DP>) => SP,
  mapDispatchToProps: (dispatch: (action: A) => void, props: $Diff<Config, SP&DP>) => DP,
  options?: {pure?: boolean, withRef: boolean}
): (component: ReactClass<Config>) => ReactClass<$Diff<Config, (SP & DP)>>;

declare function connect<Config, A: Object, SP, DP, Injected: Object, Store: Object>(
  mapStateToProps: (store: Store, props: $Diff<Config, Injected>) => SP,
  mapDispatchToProps: (dispatch: (action: A) => void, props: $Diff<Config, Injected>) => DP,
  mergeProps: (stateProps: SP, dispatchProps: DP, ownProps: $Diff<Config, Injected>) => Config,
  options?: {pure?: boolean, withRef: boolean}
): (component: ReactClass<Config>) => ReactClass<$Diff<Config, (SP & DP)>>;
```


Now, I know this super complicated. But Higher-Order-Functions are almost impossible to type with flow right now. This, as far as I know, is the most correct way to do this, but I also know it doesn't work nearly well enough. `$Diff` doesn't quite work to subtract Objects. It basically doesn't throw any errors.

I'm basically hoping that as Flow keeps getting better something like this will actually start working.

**Comment by ahutchings** [comment]
flow-typed now has libdefs for both [react-redux@4](https://github.com/flowtype/flow-typed/tree/master/definitions/npm/react-redux_v4.x.x/flow_v0.30.x-) and [react-redux@5](https://github.com/flowtype/flow-typed/tree/master/definitions/npm/react-redux_v5.x.x/flow_v0.30.x-). Can this be closed?

**Comment by nmn** [comment]
@ahutchings I'm keeping this open for now because the current libdefs for React-Redux require a LOT of manual typing. This is a different approach that does a lot more inference for you. That said this has bugs and holes.

Perhaps, it makes sense to move this PR over to flowtyped as well though. I'll look into that.

**Comment by kristian-puccio** [comment]
Are there any examples of either approach working? Most interested in checking the incoming props to the connect HOC, I've been looking for a while and have worked out how to get it to work.

**Comment by marudor** [comment]
This hasn't been updated for quite a while and I can't add commits to the PR.
If this is still relevant please submit a new PR.

**Pull request closed without merging**
