### PR TITLE
Fixes fetching and unzipping latest versions of flow [0.62+]

### LINKED ISSUE #1724: I just can't get flow-typed to fail test
No mater what I write in my test file even if it's just `hello there` I still get this:

```
flow-typed run-tests
Running definition tests in /Users/gozala/Projects/flow-typed/definitions/npm...

Fetching all Flow binaries...

All tests passed!
```

### LINKED ISSUE #1759: Missing flow binaries in local tests.
I'm having an issue getting my tests to work correctly. My current [PR build](https://travis-ci.org/flowtype/flow-typed/jobs/332878174) fails on Flow 0.62 and 0.63, but I can't get them to download and run locally:

```
$ ./run_def_tests.sh ramda_v0.x.x

...snip...

Fetching all Flow binaries...
Testing ramda_v0.x.x/flow_v0.49.x- (flow-v0.52.0)...
Testing ramda_v0.x.x/flow_v0.49.x- (flow-v0.53.0)...
Testing ramda_v0.x.x/flow_v0.49.x- (flow-v0.53.1)...
Testing ramda_v0.x.x/flow_v0.49.x- (flow-v0.54.0)...
Testing ramda_v0.x.x/flow_v0.49.x- (flow-v0.54.1)...
Testing ramda_v0.x.x/flow_v0.49.x- (flow-v0.55.0)...
Testing ramda_v0.x.x/flow_v0.49.x- (flow-v0.56.0)...
Testing ramda_v0.x.x/flow_v0.49.x- (flow-v0.57.1)...
Testing ramda_v0.x.x/flow_v0.49.x- (flow-v0.57.2)...
Testing ramda_v0.x.x/flow_v0.49.x- (flow-v0.57.3)...
Testing ramda_v0.x.x/flow_v0.49.x- (flow-v0.58.0)...
Testing ramda_v0.x.x/flow_v0.49.x- (flow-v0.59.0)...
Testing ramda_v0.x.x/flow_v0.49.x- (flow-v0.60.0)...
Testing ramda_v0.x.x/flow_v0.49.x- (flow-v0.60.1)...
Testing ramda_v0.x.x/flow_v0.49.x- (flow-v0.61.0)... <--- no 0.62 or 0.63!

All tests passed!
```

### PR DESCRIPTION
**Pull request by GAntoine**
Fixes #1759 
Fixes #1724 

@AndrewSouthpaw 
@KenanY I ended up going for a very similar fix to yours, try it out and let me know if it does the trick. If this works I'll release a patch for flow-typed.

### CODE REVIEW

**Comment by AndrewSouthpaw** [comment]
Wow that was easy. So the file name structure changed?

**Comment by GAntoine** [comment]
The name structure is the same (`flow-osx-v0.64.0.zip`), but there's an alternative release called `libflowparser-osx-v0.64.0.zip`, which was messing with one of the checks.

**Comment by AndrewSouthpaw** [comment]
Ah, got it! Thanks for fixing it. :)

**Comment by KenanY** [comment]
Yup this patch works for me as well 👍

**Pull request merged**
