### PR TITLE
Underscore: added most of the missing functions

### PR DESCRIPTION
**Pull request by doberkofler**
Added type definitions for the following methods:
where, invoke, indexBy, countBy, shuffle, toArray, unzip, lastIndexOf, sortedIndex, findLastIndex, once, after, before, wrap, negate, allKeys, invert, functions, methods, extendOwn, assign, defaults, isMatch, isElement, constant, uniqueId, escape, unescape

### CODE REVIEW

**Comment by marudor** [comment]
Could you please add tests?

**Comment by doberkofler** [comment]
@marudor Just adding all the type definitions took a lot of time and given the fact that only 2 functions had tests before, I took the liberty to create the pull request without tests. Will PR's no longer be merged without tests or is this more a friendly reminder for the future?

**Comment by doberkofler** [comment]
Some feedback would be nice (and motivating) ...

**Comment by andreiglingeanu** [comment]
Hey @doberkofler!

Writing a couple of tests is not hard at all, [here's](https://github.com/flowtype/flow-typed/pull/568/files) how I did it for `_.compose` and `_.partial`, hope it helps!

**Comment by doberkofler** [comment]
@marudor I've now added tests for the new definitions

**Comment by doberkofler** [comment]
It would be great if this pull request could be finally be committed

**Pull request merged**
