### PR TITLE
WIP: Recompose v0.21.x

### PR DESCRIPTION
**Pull request by ekosz**
This is my first foray into creating a serious flow-typing. This PR mostly piggybacks off of the great work of @gcanti at https://github.com/acdlite/recompose/pull/241. This PR takes that work and cleans it up a bit and add tests.

**Testing Checklist**
- [ ] compose,
- [x] mapProps,
- [x] withProps,
- [x] withPropsOnChange,
- [x] withHandlers,
- [x] defaultProps,
- [x] renameProp,
- [ ] renameProps,
- [x] flattenProp,
- [ ] withState,
- [x] withReducer,
- [ ] branch,
- [ ] renderComponent,
- [x] renderNothing,
- [x] shouldUpdate,
- [x] pure,
- [ ] onlyUpdateForKeys,
- [ ] withContext,
- [ ] getContext,
- [ ] lifecycle,
- [ ] toClass,
- [ ] setStatic,
- [ ] setDisplayName,
- [ ] getDisplayName,
- [ ] wrapDisplayName,
- [ ] shallowEqual,
- [ ] isClassComponent,
- [ ] createEagerElement,
- [ ] createEagerFactory,
- [ ] createSink,
- [ ] componentFromProp,
- [ ] nest,
- [ ] hoistStatics

### CODE REVIEW

**Comment by ekosz** [comment]
Some initial questions I have for the maintainers:

1. What version of flow should I be targeting? Currently I just picked 0.38 as thats most recent, but would you like these typings to support older versions?
1. I don't know flow that well, but it seems that some of the error call sites are a little off/confusing. For example https://github.com/ekosz/flow-typed/blob/b1cb5fd300880d96d6d0620920ef44d88b573576/definitions/npm/recompose_v0.21.x/test_recompose_v0.21.x.js#L86-L88 I would have thought the error would occer on line 88, not 86. Is there something I can do to the typings to make the errors more human friendly to track down?
1. I can't seem to get the typing test for `setState` to fail. https://github.com/ekosz/flow-typed/blob/b1cb5fd300880d96d6d0620920ef44d88b573576/definitions/npm/recompose_v0.21.x/test_recompose_v0.21.x.js#L141-L142 For some reason its dropping/not using the typing of the initial setter function? Any help in the right direction would be super appreciated.

**Comment by lewisf** [comment]
Is there anything I can do to help out with this to take this to the finish line?

**Comment by ekosz** [comment]
@lewisf Hey Lewis, sorry I dropped the ball on this one. If you'd like I'd be more than happy giving you contributor access to this branch if you would like to take it over the finish line. Or you can copy the code to your own PR and I can close this one.

**Comment by lewisf** [comment]
no problem :) thanks for doing so much already.

@swang-coursera and I can take over -- we'll copy to another PR but let's leave this open for now until we get to it.

**Comment by shuhei** [comment]
@ekosz @lewisf Hi! Here are my 2 cents extending the work by @ekosz but I also stopped working on it.

https://github.com/shuhei/typed-recompose

Its README explains some caveats like one for suppress_comment.

**Comment by TrySound** [comment]
Recompose officially supports flow, so this pr can be closed.

**Comment by GAntoine** [comment]
Closing as per TrySound's comment, and since there's already a definition for recompose 0.24.x.

**Pull request closed without merging**
