### PR TITLE
Apollo Client v0.4.x

### PR DESCRIPTION
**Pull request by joarwilk**
Copied and modified the typescript definition files. It's incomplete, but it covers most (if not all) of the public-facing API.

The test is fairly useless, would appreciate some pointers there. Not sure which level of granularity it should be.

### CODE REVIEW

**Comment by jbaxleyiii** [comment]
@joarwilk this looks pretty great! I'll try it out in a sample app this week if I can find some time! Any plans to do react-apollo as well?

**Comment by joarwilk** [comment]
@jbaxleyiii yep, will create a react-apollo PR today. It has slightly too many `any` types however so I'm trying to see what I can do to make it more strict

**Comment by marudor** [comment]
Looks great.
@jbaxleyiii did you test it yet?
I'm no apollo expert. So I can't say much about quality. Just that the types look good.

**Comment by alexeygolev** [comment]
@joarwilk any luck with react-apollo? I'm playing around with typing it as well but would love to discuss possible approaches

**Comment by joarwilk** [comment]
@alexeygolev I got very tired of writing library definitions so I wrote a typescript->flow definition converter. It's not finished yet but its quite close.

You can follow / contribute here: https://github.com/joarwilk/typedef-converter

**Comment by jfuchs** [comment]
@joarwilk: do you still plan on merging this PR? I've taken a look at just running `genflow` against apollo-client, but that still seems a little more manual than would be ideal.

**Comment by joarwilk** [comment]
@jfuchs This PR is so outdated it's better to close it and start over imo. I currently dont have the time to finish it, unfortunately.

**Comment by marudor** [comment]
Closing just as @joarwilk suggests.
If someone wants to pick this up please create a new PR!

**Pull request closed without merging**
