### PR TITLE
New algoliasearch

### PR DESCRIPTION
**Pull request by jpolo**
Add typing for algolia search

This is not exhaustive for all functionnalities but it's a good stard

### CODE REVIEW

**Comment by AndrewSouthpaw** [comment]
Build is still failing.

**Comment by jpolo** [comment]
I am unable to reproduce on my machine... When I run "node dist/cli.js run-tests" everything is passing

**Comment by jpolo** [comment]
I don't understand why it is failing only on Node 8...

**Comment by AndrewSouthpaw** [comment]
Try rebuilding it? Sometimes the repo tests are flaky.

**Pull request closed without merging**
