### PR TITLE
Adds express$Router.param

### PR DESCRIPTION
**Pull request by kennethaasan**
I saw that express missed express$Router.param (http://expressjs.com/en/api.html#app.param). I'm not sure if I typed it 100% correct, but it works in my project.

Best Regards,
Kenneth

### CODE REVIEW

**Comment by GAntoine** [comment]
Related to #409

**Comment by GAntoine** [comment]
Judging from the failing specs, it looks like your def isn't compatible with flow 32 or 33..

**Comment by kennethaasan** [comment]
Hi @GAntoine,

Tests are passing now. I've never worked with such a old version of flow, so I didn't know this syntax :)

Anything else I should add/fix?

**Comment by GAntoine** [comment]
Nope, this looks good to me, I'll go ahead and merge it. Thanks for the fix 💪

**Pull request merged**
