### PR TITLE
react-modal: able to use promise for onAfterOpen

### PR DESCRIPTION
**Pull request by sottar**
I wanna use async function for onAfterOpen function in react-modal package.
I thought these codes can fix this.
Please review or comments 🙏

### CODE REVIEW

**Comment by GAntoine** [comment]
@sottar Could you add a test to cover the change?

**Comment by sottar** [comment]
@GAntoine Thanks comment!!  I added test. So check it please 🙏

**Comment by GAntoine** [comment]
@sottar プルのリクエストをありがとう！

**Comment by sottar** [comment]
@GAntoine thank you for your Japanese comment XD

**Pull request merged**
