### PR TITLE
Styled-Components: Added more robust type checking for default DOM elements

### PR DESCRIPTION
**Pull request by mwalkerwells**
Addresses: https://github.com/flowtype/flow-typed/pull/1075#issuecomment-318918689

### CODE REVIEW

**Comment by johnhaley81** [comment]
💯 Thanks for the fix!

**Comment by johnhaley81** [comment]
@mwalkerwells is there a way to have the props that are passed into functions in the context type checked as well? Right now it's breaking any calculated styles :(

Ex:

```javascript
const foo = styled.css`
  color: ${({ color }: { color?: string }) => color || 'black'}
`;
```

The above code now yields the following error: 
image

**Comment by mwalkerwells** [comment]
I didn't even look at those functions, but this should fix it. Added tests to catch it in the future.

**Comment by johnhaley81** [comment]
Just tested this locally. All good :)

**Comment by mwalkerwells** [comment]
@marudor You're a computer (I think), but can you merge?

**Comment by mwalkerwells** [comment]
Oh, maybe not?

**Comment by GAntoine** [comment]
New Marudor™ merge commands: `marudor merge mwalkerwells:styled-components-tagged-template-literal flowtype:master --squash`

@mwalkerwells In all seriousness he's very much human. Or maybe that's what they want us to think...

**Comment by SBoudrias** [comment]
Hey, this update broke for us. The updated `attrs()` definition disallow pass through properties that get passed to the DOM component. e.g.

```js
const Comp = styled.div.attrs({
    classNames: props => classnames({ 'is-active': props.active }),
})`
    padding: 10px;
`;

<Comp active onClick={handler} />
```

It'll throw that the component doesn't have a `onClick` property. More annoying, this happens with the children property too:

```
09:47:43 Error: components/List/test.js:10
09:47:43  10:         const selector = shallow(<ListItem isActive isLocked />);
09:47:43                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element `ListItem`
09:47:43                          v--------
09:47:43 123:                     <ListItem
09:47:43 124:                         isActive={item.id === current}
09:47:43 125:                         onClick={() => onSelect(item.id)}
09:47:43 126:                         className="AASubList-item"
09:47:43 127:                     >
09:47:43                          ^ property `children`. Property not found in. See: components/List/index.js:123
09:47:43  10:         const selector = shallow(<ListItem isActive isLocked />);
09:47:43                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ props of React element `ListItem`
09:47:43 
```

**Comment by mwalkerwells** [comment]
@SBoudrias Can you post a narrowly-scoped example of the issue? Your error does not correspond with your code.

Trying to recreate your example, I also do not get an error:
```js
import styled from 'styled-components'

declare var classnames: Object => string
declare var handler: void => void

const Comp = styled.div.attrs({
    classNames: props => classnames({ 'is-active': props.active }),
})`
    padding: 10px;
`;

<Comp active onClick={handler} />

```

**Comment by mwalkerwells** [comment]
If we can narrow it down, please add a test so we don't break it in the future. This what you're talking about?

```js
import styled from 'styled-components'

const HasFoo = styled.div.attrs({
    foo: 'bar'
})`
    padding: 10px;
`;

declare var needsOnClickerReactElement: React$Element<{ foo: 'bar' }> => void

needsOnClickerReactElement(<HasFoo />)

```

```js
declare var needsOnClickerReactElement: React$Element<{ foo: 'bar' }> => void
                                                      ^^^^^^^^^^^^^^ property `foo`. Property not found in
needsOnClickerReactElement(<HasFoo />)
                           ^^^^^^^^^^ props of React element `HasFoo`
```

**Comment by SBoudrias** [comment]
@mwalkerwells hum, I haven't been able to write a reduced failing cases yet. Seems like the problem is more complex that I initially though. As soon as I updated to the latest type def from yesterday, it raised ~30 new errors in our code base. Replacing the typing with `attrs: any` force fixed the issue for now.

The error I see is always about native DOM element props that aren't always passed. For now I can see all the errors have this in common:

1. They're all component created with `styled.x.attrs()` or `styled(x).attrs()`
2. Errors are about native DOM element props; e.g. `onMouseEnter`, `children`, `className`
3. The component must be created multiple times with different set of property. e.g. `<A onClick={x} />`, `<A />`, `<A className="hey" />` (components used only once or always with the same signature aren't causing this issue)

I'll try to get a reduced test case, but I haven't figured it out yet.

**Comment by SBoudrias** [comment]
For some reason, when I put all code into the same file, it stops working. But if it's in many files, then it fails. Check this one:

```
Error: components/Badge/test.js:8
  8:         expect(shallow(<Badge />)).toMatchSnapshot();
                            ^^^^^^^^^ React element `Badge`
  8:         expect(shallow(<Badge />)).toMatchSnapshot();
                            ^^^^^^^^^ props of React element `Badge`. This type is incompatible with
                   v------------------
  6: const Badge = styled.span.attrs({
  7:     style: props => ({
  8:         color: props.color || 'inherit',
  9:     }),
 10: })`
     -^ union: props of React element `Badge`(s). See: components/Badge/index.js:6
  Member 1:
   19: const BetaBadge = () => <Badge color={colors.brand.aaBlue}>beta</Badge>;
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ props of React element `Badge`. See: components/Badge/index.js:19
  Error:
   19: const BetaBadge = () => <Badge color={colors.brand.aaBlue}>beta</Badge>;
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ property `children`. Property not found in. See: components/Badge/index.js:19
    8:         expect(shallow(<Badge />)).toMatchSnapshot();
                              ^^^^^^^^^ props of React element `Badge`
  Member 2:
   17: const NewBadge = () => <Badge color={colors.brand.aaBlue}>new</Badge>;
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ props of React element `Badge`. See: components/Badge/index.js:17
  Error:
   17: const NewBadge = () => <Badge color={colors.brand.aaBlue}>new</Badge>;
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ property `children`. Property not found in. See: components/Badge/index.js:17
    8:         expect(shallow(<Badge />)).toMatchSnapshot();
                              ^^^^^^^^^ props of React element `Badge`
  Member 3:
   15: const PremiumBadge = () => <Badge color={colors.brand.persianGreen}>premium</Badge>;
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ props of React element `Badge`. See: components/Badge/index.js:15
  Error:
   15: const PremiumBadge = () => <Badge color={colors.brand.persianGreen}>premium</Badge>;
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ property `children`. Property not found in. See: components/Badge/index.js:15
    8:         expect(shallow(<Badge />)).toMatchSnapshot();
                              ^^^^^^^^^ props of React element `Badge`
```

The component:

```js
// @flow
import React from 'react';
import styled from 'styled-components';
import * as colors from '../style/colors';

const Badge = styled.span.attrs({
    style: props => ({
        color: props.color || 'inherit',
    }),
})`
    font-size: 9px;
    text-transform: uppercase;
`;

const PremiumBadge = () => <Badge color={colors.brand.persianGreen}>premium</Badge>;

const NewBadge = () => <Badge color={colors.brand.aaBlue}>new</Badge>;

const BetaBadge = () => <Badge color={colors.brand.aaBlue}>beta</Badge>;

export default Badge;
export { PremiumBadge, NewBadge, BetaBadge };
```

The test:
```js
// @flow
import React from 'react';
import { shallow } from 'enzyme';
import Badge, { PremiumBadge, BetaBadge, NewBadge } from '.';

describe('<Badge>', () => {
    it('render badge', () => {
        expect(shallow(<Badge />)).toMatchSnapshot();
        expect(shallow(<PremiumBadge />)).toMatchSnapshot();
        expect(shallow(<BetaBadge />)).toMatchSnapshot();
        expect(shallow(<NewBadge />)).toMatchSnapshot();
    });
});
```

It seems like it's aggregating the types from the different Badges type components and applying them to the base `<Badge />`; making `children` a required prop.

**Comment by mwalkerwells** [comment]
Modules behave differently across module boundaries. https://github.com/facebook/flow/issues/1278

There's a lot of code here & I think it comes down to the type of ```shallow```.

**Comment by mwalkerwells** [comment]
Looks like ```shallow``` expects ```React$Element<any>```, so that should not be the problem. I cannot reduce your repo down to anything that gives an error. Can you please reduce your example to include only the bare minimum?

**Comment by mwalkerwells** [comment]
Also, what version of flow are you using?

**Comment by SBoudrias** [comment]
Using latest `0.52.0`. I'll try to reduce and a clonable example.

**Pull request merged**
