### PR TITLE
[moment_v2.x] update based on the official included typescript file

### PR DESCRIPTION
**Pull request by rosskevin**
I started from scratch with the official `moment.d.ts` from `2.18.1`, used `flowgen`, then cleaned up the module namespacing.

### CODE REVIEW

**Comment by rosskevin** [comment]
I will look at these CI errors and fix.

**Comment by rosskevin** [comment]
I could use some help from someone here, many of the errors are completely expected, with `$ExpectError`, for example:

```js
// $ExpectError
moment().calendar(null, {
  sameElse: () => {},  // L52
});
```

```
0-test_moment-v2.js:52
    52:   sameElse: () => {},
                         ^ undefined. This type is incompatible with
    57:   declare type CalendarSpecVal = string | ((m?: MomentInput, now?: Moment) => string);
                                                                                      ^^^^^^ string. See lib: moment_v2.x.x.js:57
```
I'm not sure why the `$ExpectError` is not having any effect.

**Comment by rosskevin** [comment]
@marudor any thoughts on why `$ExpectError` isn't working as expected in this case?

**Comment by marudor** [comment]
Error is on Line 52, your $ExpectError on Line 50 - therefore only expected on Line 51?

**Comment by rosskevin** [comment]
I tried moving it down with the same result. This is actually untouched test code that was working...so I'm confused.

**Comment by marudor** [comment]
Will take a look later.

**Comment by rosskevin** [comment]
I've just updated this and still have no idea why tests don't run.  There is quite a bit of work put into this, anyone else is free to take it over.  I'm using it locally successfully.

**Comment by GAntoine** [comment]
How are you importing the typedef locally? The error in the spec is **Default import from `moment`. This module has no default export. Did you mean `import {Moment} from "moment"`?** This leads me to believe the test file for this def is importing incorrectly.

**Comment by GAntoine** [comment]
Closing as there is a new, updated definition for moment v2.

**Pull request closed without merging**
