### PR TITLE
The Sindre Sorhus Suite

### PR DESCRIPTION
**Pull request by thejameskyle**
Here are a bunch of definitions for @sindresorhus's most popular packages.

### CODE REVIEW

**Comment by ctrlplusb** [comment]
Please keep up this aggressiveness x

**Comment by thejameskyle** [comment]
Finally figured out why I couldn't run the tests locally. The version of Jest being used doesn't support Node 6

**Comment by freebroccolo** [comment]
Nice. I was going to mention that I wrote an [interface for chalk](https://github.com/freebroccolo/flow-chalk/blob/master/sig/index.js) but I see you've added one to this repo already. Looks like my version is a little different though. Anyway, if there's something useful there, feel free to take it.

**Comment by jeffmo** [comment]
This PR is amazing!! :D

I made a few follow-up tweaks over in https://github.com/flowtype/flow-typed/pull/184, FYI

**Comment by jeffmo** [comment]
> The version of Jest being used doesn't support Node 6

Just pushed https://github.com/flowtype/flow-typed/commit/aca91e43241f054e3899cf61034553ef64b12895 to bump to the latest version of Jest (with node 6 support)

**Comment by sindresorhus** [comment]
Oh wow. This is most excellent. Great work @thejameskyle. I appreciate the effort :)

**Pull request merged**
