### PR TITLE
[libdef] slug v 0.9.x

### PR DESCRIPTION
**Pull request by alexeygolev**

### CODE REVIEW

**Comment by ckknight** [comment]
`SlugOptions` should be used as `$Shape<SlugOptions>` or similar because `slug('some string', { mode: 'rfc3986' });` should be completely valid, despite not having all properties of `SlugOptions`

**Comment by jeffmo** [comment]
@ckknight: Mind sending a pull request?

**Comment by ckknight** [comment]
Yeah, I can when I get home - `flow-typed run-tests` won't work behind my corporate network, apparently.

**Comment by jeffmo** [comment]
Ah, yea `run-tests` needs to be able to download the flow binaries from github to run the tests.
(Maybe you need to set HTTP_PROXY? ....or just do it at home :) )

**Pull request merged**
