### PR TITLE
Fully support array arguments in classnames

### PR DESCRIPTION
**Pull request by silvenon**
Other than strings, array arguments can contain objects and falsy values. Arrays are just flattened.

### CODE REVIEW

**Comment by GAntoine** [comment]
@lifeiscontent Would you mind reviewing this change? Seems you've worked on this libdef in the past.

**Comment by silvenon** [comment]
Give me a moment to add tests. I was lazy when I submitted this PR.

**Comment by lifeiscontent** [comment]
@GAntoine LG2M :shipit:

**Comment by silvenon** [comment]
It doesn't pass the tests yet, I should add a test for this and I should also add the definition for earlier versions of Flow.

For some reason `./run_def_tests.sh classnames` runs everything always, so my iteration process is slower. I will let you know when I'm done, sorry. 😄

**Comment by GAntoine** [comment]
You can use `node dist/cli.js run-tests classnames` to run just the tests for `classnames`. Should speed up your process quite a bit. 💨

**Comment by silvenon** [comment]
All done!

**Comment by silvenon** [comment]
Done. Just wanted to extract changes caused by Prettier into a separate commit.

**Comment by Mr-Wallet** [comment]
This appears to have broken arrays of strings (i.e. `classNames(['a', 'b', 'c'])`).

It gives the error: `Cannot call `classnames` because string [1] is incompatible with object type [2] in array element of array element.`

**Comment by silvenon** [comment]
Weird, because this test passes: https://github.com/flowtype/flow-typed/blob/60fd29d2cf0f0a539024c908351997d0cd3755a8/definitions/npm/classnames_v2.x.x/test_classnames_v2.x.x.js#L18

Which version of Flow are you using?

**Comment by Mr-Wallet** [comment]
I'm on the latest version. I think the issue may be the fact that the argument list is spread into an "array", and the case I'm having trouble with is when the entire argument list is... just a single array, and Flow is getting confused. Notably, none of the test cases test a single array as the only argument.

**Comment by silvenon** [comment]
```js
classnames(["a", "b", "c"]);
```
```
❯ node cli/dist/cli.js run-tests "classnames"
Running definition tests against latest 15 flow versions in /Users/silvenon/Code/flow-typed/definitions/npm...

Fetching all Flow binaries...
Finished fetching Flow binaries.

Testing classnames_v2.x.x/flow_v0.25.x- (flow-v0.56.0)...
Testing classnames_v2.x.x/flow_v0.25.x- (flow-v0.57.1)...
Testing classnames_v2.x.x/flow_v0.25.x- (flow-v0.57.2)...
Testing classnames_v2.x.x/flow_v0.25.x- (flow-v0.57.3)...
Testing classnames_v2.x.x/flow_v0.25.x- (flow-v0.58.0)...
Testing classnames_v2.x.x/flow_v0.25.x- (flow-v0.59.0)...
Testing classnames_v2.x.x/flow_v0.25.x- (flow-v0.60.0)...
Testing classnames_v2.x.x/flow_v0.25.x- (flow-v0.60.1)...
Testing classnames_v2.x.x/flow_v0.25.x- (flow-v0.61.0)...
Testing classnames_v2.x.x/flow_v0.25.x- (flow-v0.62.0)...
Testing classnames_v2.x.x/flow_v0.25.x- (flow-v0.63.0)...
Testing classnames_v2.x.x/flow_v0.25.x- (flow-v0.63.1)...
Testing classnames_v2.x.x/flow_v0.25.x- (flow-v0.64.0)...
Testing classnames_v2.x.x/flow_v0.25.x- (flow-v0.65.0)...
Testing classnames_v2.x.x/flow_v0.25.x- (flow-v0.66.0)...

All tests passed!
```

And it doesn't seem to be a false positive, as soon as I add an invalid value like this:

```js
classnames(["a", "b", 5]);
```

it fails as expected.

**Comment by silvenon** [comment]
Is your described Flow error the entire output? If not, can you paste the whole thing?

**Comment by Mr-Wallet** [comment]
Thanks for taking the time to dig into this and follow up. I can't seem to consistently get flow to complain about this problem in my React app by simply trying to repro in a random place, but here's the particular error I'm getting (with some irrelevant props removed for brevity):
```
Error: myComponent.jsx:59
 59:         <div className={classnames(myClasses)}>
                             ^^^^^^^^^^^^^^^^^^^^^^ rest parameter array of call of `classnames`. Has some incompatible type argument with
 13:     ...classes: Array<$npm$classnames$Classes | $npm$classnames$Classes[]>
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ array type. See lib: myProject/flow-typed/npm/classnames_v2.x.x.js:13
  Type argument `T` is incompatible:
     59:         <div className={classnames(myClasses)}>
                                            ^^^^^^^^^^ array type. Has some incompatible type argument with
     13:     ...classes: Array<$npm$classnames$Classes | $npm$classnames$Classes[]>
                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^ array type. See lib: myProject/flow-typed/npm/classnames_v2.x.x.js:13
      Type argument `T` is incompatible:
         25:   myClasses?: string[] | { [name: string]: boolean },
                            ^^^^^^ string. This type is incompatible with
         13:     ...classes: Array<$npm$classnames$Classes | $npm$classnames$Classes[]>
                                                             ^^^^^^^^^^^^^^^^^^^^^^^ object type. See lib: myProject/flow-typed/npm/classnames_v2.x.x.js:13
```

It's possible that the union type for `myClasses` is what's confusing Flow, but I've tried taking an `any` and casting it to `string[] | { [name: string]: boolean }` as I pass it into `classnames` and I don't get an error.

**Comment by silvenon** [comment]
Yep, this fails:

```js
const myClasses: string[] = ["foo", "bar", "baz"]
classnames(myClasses)
```

```
Cannot call `classnames` because string [1] is incompatible with object type [2] in array element of array element.

  0-test_classnames_v2.x.x.js:27:1
  27| classnames(myClasses)
      ^^^^^^^^^^^^^^^^^^^^^

References:
  0-test_classnames_v2.x.x.js:26:18
  26| const myClasses: string[] = ["foo", "bar", "baz"]
                        ^^^^^^ [1]
  classnames_v2.x.x.js:10:49
  10|     ...classes: Array<$npm$classnames$Classes | $npm$classnames$Classes[]>
                                                      ^^^^^^^^^^^^^^^^^^^^^^^ [2]
```

I currently have no idea why. I'll dig further, thanks for reporting. 👍

**Pull request merged**
