### PR TITLE
Code cleanup + limit libdef versions to numbers+wildcards

### PR DESCRIPTION
**Pull request by jeffmo**
This PR does a few things at once (sorry about that), but the biggest thing is that it no longer allows `>=` or `<=` on package version names (only `x` wildcards).

Also it:
* Consolidates validation logic with the logic that scans the `/definitions` dir for info (DRY cleanup).
* Adds jest + tests some of the semver library code

Once this lands, I'll rebase https://github.com/flowtype/flow-typed/pull/23 on top of this and hopefully our path forward will be a little more clear

### CODE REVIEW

**Comment by jeffmo** [comment]
Hoping to figure out the [`jest` issues](https://github.com/flowtype/flow-typed/pull/23#issuecomment-207425675) before this PR lands. Heading home now, but plan to dig back in later tonight.

**Comment by splodingsocks** [comment]
I'll take a crack-o-la at it this morning

**Comment by splodingsocks** [comment]
Alrighty, for now I've slapped a band-aid on the jest issues by just adding `node_modules` and `dist` to the paths that Jest won't mock. Now the tests are passing. If we want to invest more time later in debugging jest in combination with request we can, but for now I want to get some stuff DONE!

**Comment by splodingsocks** [comment]
Nice, upgrading to http://facebook.github.io/jest/blog/2016/04/12/jest-11.html helps out the issues with automocking, which in turn helps out the issues with `request`

**Comment by jeffmo** [comment]
#herostatus

**Pull request merged**
