### PR TITLE
Add definitions for other Observable methods

### PR DESCRIPTION
**Pull request by mcortesi**
Observable.timer:
http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#static-method-timer

Observable.repeat:
http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-repeat

### CODE REVIEW

**Comment by mcortesi** [comment]
I don't know why travis is failing. 

I tried running it on my computer `npm run clean && npm run build && npm run test-quick` and everything's green!

**Comment by marudor** [comment]
I've merged master into this - didn't really do anything.
I'Ve got no Idea what the problem is.
@jeffmo could you take a look?

**Comment by GAntoine** [comment]
This may be a dumb comment, but does it have to do with `const numbers` being defined twice in the same scope (test_rxjs.js, line 5 and 20)?

**Comment by marudor** [comment]
Yes it does have to do with that.
Guess I missed that.
Fixed and merged.

**Pull request merged**
