### PR TITLE
Switched most examples to use yarn over npm

### PR DESCRIPTION
**Pull request by uri**
Replaces #459

### CODE REVIEW

**Comment by ajhyndman** [comment]
Oh, thanks for picking this up!  Sorry, I missed he earlier request somehow.

**Comment by 102** [comment]
@GAntoine empty `yarn.lock` have been added to the root of the project in this PR. Is it intended?

**Comment by GAntoine** [comment]
I don't think it was intentional. Is it causing issues?

**Comment by 102** [comment]
I haven't met any yet. @uri, is it safe to remove the lock?

**Comment by GAntoine** [comment]
@102 I work with him, he says we're good to remove it.

**Pull request merged**
