### PR TITLE
[Ramda] Fix ramda sortBy typedef, add test

### PR DESCRIPTION
**Pull request by korbin**
Ramda sortBy only accepts two arguments:

http://ramdajs.com/docs/#sortBy

This PR fixes that problem and adds a test for the curried/total cases.

### CODE REVIEW

**Comment by korbin** [comment]
cc @alexeygolev

**Comment by alexeygolev** [comment]
@korbin Nice!

**Comment by marudor** [comment]
This should've been merged earlier!

**Comment by alexeygolev** [comment]
@marudor thanks!

**Pull request merged**
