### PR TITLE
Added temporary stubs for mongodb to avoid errors

### PR DESCRIPTION
**Pull request by mjomble**
See https://github.com/flowtype/flow-typed/pull/1473#issuecomment-345252760

### CODE REVIEW

**Comment by nodkz** [comment]
# [WIP] DO NOT MERGE THIS PR

Guys, can we strip out `MongoDB$ObjectID` from this package to the new `bson` package (https://github.com/mongodb/js-bson) where it really implemented.

So I'll replace my `BSONObjectId` from upcoming PR  to `mongoose` declarations https://github.com/flowtype/flow-typed/pull/1557.

Better to have all in sync and do not duplicate types.

@sibelius can you create the new `bson` package, where for now, will be only one declaration `BSON$ObjectID`?

Thx.

**Comment by nodkz** [comment]
`Mongoose`, `mongodb-core` and 280 more packages depend on `bson` (2.2M downloads/month):
https://www.npmjs.com/browse/depended/bson

**Comment by sibelius** [comment]
I think `bson` package would make more sense

**Comment by mjomble** [comment]
Sounds good to me. Shall I close this PR?

**Comment by nodkz** [comment]
No. Firstly somebody should create declarations for `bson` package.
I'm really busy for this two weeks and can not do it myself.

Who can solve this?

**Comment by nodkz** [comment]
Did it myself in #1572 
Waiting while it will be merged.

**Comment by nodkz** [comment]
Shit happens.
Flow-typed declarations do not support global imports. So using copy-paste of needed classes, like it did in #1585

**Comment by nodkz** [comment]
@GAntoine please merge this PR.

Nothing todo here.

**Pull request merged**
