### PR TITLE
Update libdef for redux-actions v2.x.x

### PR DESCRIPTION
**Pull request by floriangosse**
Action creators now fully accept multiple arguments.

### CODE REVIEW

**Comment by showmeyourhits** [comment]
It is really surprizing, that this bug exists.
I wonder: is it bad practice to pass multiple arguments to payloadCreator?

**Comment by floriangosse** [comment]
I don't think that is bad practice because otherwise we don't need a payload create function because we could simply set the first argument (which would be an object if we have multiple arguments) as payload. But this whole process makes the payload creator obsolete for the most parts.

**Comment by dignifiedquire** [comment]
I started using this  and it works very well for me 👍

**Comment by floriangosse** [comment]
Maybe someone of the contributors could help me with the error.
// cc @marudor

**Comment by GAntoine** [comment]
@floriangosse `redux-actions_v2.x.x` has an existing definition, where the flow version is `flow_v0.34.x-`. Change that folder's name to `flow_v0.34.x-0.38.x`, and your version will be used when flow's version is 39 or higher.

**Comment by floriangosse** [comment]
@GAntoine thank you. I will change it.

**Pull request merged**
