### PR TITLE
Fix swagger-schema-official version

### PR DESCRIPTION
**Pull request by StefanoMagrassi**
Fix swagger-schema-official directory name in order to match prerelease version

### CODE REVIEW

**Comment by StefanoMagrassi** [comment]
Travis job throws this weird error for nodejs 8...

`ERROR: Error finding latest commit hash for definitions/npm/underscore_v1.x.x/flow_v0.38.x-/underscore_v1.x.x.js: undefined`

**Comment by pconerly** [comment]
This change is causing a failure for me when I run `flow-typed install`

```
[peterconerly@sandbox]$ flow-typed install
• Found flow-bin@v0.45.0 installed. Installing libdefs compatible with this version of Flow...
• Found 117 dependencies in package.json. Searching for libdefs...
• flow-typed cache not found, fetching from GitHub...done.
UNCAUGHT ERROR: Error: swagger-schema-official_v2.x.x-: 'swagger-schema-official_v2.x.x-' is a malformed definitions/npm/ directory name! Expected the name to be formatted as <PKGNAME>_v<MAJOR>.<MINOR>.<PATCH>
    at validationError (/Users/peterconerly/.nvm/versions/node/v7.0.0/lib/node_modules/flow-typed/dist/lib/libDefs.js:804:11)
    at parseRepoDirItem (/Users/peterconerly/.nvm/versions/node/v7.0.0/lib/node_modules/flow-typed/dist/lib/libDefs.js:731:5)
    at addLibDefs$ (/Users/peterconerly/.nvm/versions/node/v7.0.0/lib/node_modules/flow-typed/dist/lib/libDefs.js:304:27)
    at tryCatch (/Users/peterconerly/.nvm/versions/node/v7.0.0/lib/node_modules/flow-typed/node_modules/regenerator-runtime/runtime.js:64:40)
    at Generator.invoke [as _invoke] (/Users/peterconerly/.nvm/versions/node/v7.0.0/lib/node_modules/flow-typed/node_modules/regenerator-runtime/runtime.js:355:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/peterconerly/.nvm/versions/node/v7.0.0/lib/node_modules/flow-typed/node_modules/regenerator-runtime/runtime.js:116:21)
    at tryCatch (/Users/peterconerly/.nvm/versions/node/v7.0.0/lib/node_modules/flow-typed/node_modules/regenerator-runtime/runtime.js:64:40)
    at invoke (/Users/peterconerly/.nvm/versions/node/v7.0.0/lib/node_modules/flow-typed/node_modules/regenerator-runtime/runtime.js:154:20)
    at /Users/peterconerly/.nvm/versions/node/v7.0.0/lib/node_modules/flow-typed/node_modules/regenerator-runtime/runtime.js:201:11
    at callInvokeWithMethodAndArg (/Users/peterconerly/.nvm/versions/node/v7.0.0/lib/node_modules/flow-typed/node_modules/regenerator-runtime/runtime.js:200:16)

```

**Comment by mat1h** [comment]
👆 +1

**Comment by pconerly** [comment]
@mat1h I was able to get a temporary fix by:

```
cd ~/.flow-typed/repo
git rm -r definitions/npm/swagger-schema-official_v2.x.x-/
git commit -m "Remove swagger"
```
Then you won't have swagger, but flow-typed will still be able to rebase on master.  (You won't be able to rebase if you are uncommitted changes.)

**Comment by StefanoMagrassi** [comment]
@pconerly @mat1h take a look here -> [#905](https://github.com/flowtype/flow-typed/issues/905#issuecomment-305408803)

**Pull request merged**
