### PR TITLE
[react-transition-group] Replace an interface with an object type

### PR DESCRIPTION
**Pull request by maxmalov**
Looks like flow doesn't work well with interface and types intersections

### CODE REVIEW

**Comment by maxmalov** [comment]
Still, a WIP, while I'm reproducing the error in tests from my project case

**Comment by AndrewSouthpaw** [comment]
Go ahead and ping me when it's no longer a WIP.

**Comment by maxmalov** [comment]
@AndrewSouthpaw added a test case to reproduce an issue

**Comment by AndrewSouthpaw** [comment]
Looks good, thanks!

**Pull request merged**
