### PR TITLE
adjust exressjs router

### PR DESCRIPTION
**Pull request by asci**
it is possible to use a router without root path [Expressjs docs](http://expressjs.com/en/4x/api.html#router)

### CODE REVIEW

**Comment by philikon** [comment]
This should already be handled by
```
  use(middleware: express$Middleware): this;
```
because `express$Router` implements the `express$Middleware` callable signature.

**Comment by GAntoine** [comment]
@asci Are you interested in bringing this PR up to date, or are we good to close it? I can't judge the accuracy of philikon's comment, or the change itself.

**Comment by asci** [comment]
I'll update on the weekend

**Comment by asci** [comment]
sorry, I had a busy weekend, will update as soon as possible

**Comment by GAntoine** [comment]
Closing as the current definition already allows for it.

**Pull request closed without merging**
