### PR TITLE
make libdefs for marked global under marked$*

### PR DESCRIPTION
**Pull request by Kriegslustig**
This  PR makes all libdefs for marked global under `marked$[...]`.

### CODE REVIEW

**Comment by ryyppy** [comment]
I don't know `marked`, but is it really necessary to put everything in the global scope?
Why is it not in the `declare module` scope?

**Comment by Kriegslustig** [comment]
You're probably right. It's not necessary in most use-cases. `marked` has a pretty flexible system for extension. For example `marked-man` is a package that just extends `marked` and adds the ability to format the output as `roff`. So for the `marked-man` libdef it would be necessary to access the `marked` libdef.

But since we can't define dependencies between libdefs, I had to copy over the `marked` libdef to the `marked-man` libdef. In `marked-man`'s libdefs I declared the `marked` libdefs in global-scope as well. Redeclaring the `marked` libdefs inside the `marked-man` module scope would technically be incorrect. Since users could then for example import `marked`'s `Lexer` directly from `marked-man`. Which would be incorrect.

Also; if a user wanted to write their own extension of `marked` though it might be useful to have them available globally. **I thought there was probably no harm to declaring them globally with the `$`-convention.**

Do you think we should leave them inside the module scope and have users copy them over?

**Comment by ryyppy** [comment]
Yeah, for extensions it is reasonable... I wonder if there will be a possibility to do `import type from 'somepkg'` in declaration files soon? Then it would be a no-brainer to just declare reusable types in the `declare module` scope... anyways, other than that I don't see any problems with this

**Comment by Kriegslustig** [comment]
For that to work, libdefs would need to be able to reference their dependencies (including the required version). You probably know this, but a solution is beeing worked on [here](https://github.com/flowtype/flow-typed/issues/16).

**Pull request merged**
