### PR TITLE
Added definitions for jquery. (#384)

### PR DESCRIPTION
**Pull request by doberkofler**

### CODE REVIEW

**Comment by marudor** [comment]
Nice.
It looks pretty good. But could someone who is using jQuery check it on their codebase? Would like to get some feedback before merging it.

**Comment by doberkofler** [comment]
@marudor I'm actually using the type definitions in a very large application. Currently i need to find a way on how to deal with the fact that I still have not found a way on how to extend the existing jquery interfaces with all the plugins that i need without having to modify the definition file itself . Any help would be appreciated.

**Comment by doberkofler** [comment]
@marudor I did some quite extensive testing with the new definitions and I actually did find a few minor problems that I've already fixed.

**Comment by doberkofler** [comment]
@marudor Anything else I can do, to get this merged? (I spend lot of time on this)

**Pull request merged**
