### PR TITLE
Improve moment.duration definitions a bit

### PR DESCRIPTION
**Pull request by futpib**
This allows handy import like
```js
import { duration } from 'moment';
```

And adds some pretty simple duration type tests.

### CODE REVIEW

**Comment by futpib** [comment]
Please don't merge yet, I just realized this breaks CommonJS imports, gonna try to fix that

**Comment by futpib** [comment]
No luck on trying to make this work with both es6 import and commonjs (01239e1e).

With `declare module.exports: Class<moment$Moment>;` this fails (even thought moment.duration is defined in the `moment$Moment` class, even if I change it from a static method to a static property):
```js
import { duration } from 'moment';
```

With es6 export definitions, test from 01239e1e fail.

And you can't have both declared 😕.

Any advice on this?

**Comment by marudor** [comment]
@jeffmo Any Idea about the es6/commonjs issue?

**Comment by GAntoine** [comment]
@futpib Is this change still relevant?

**Pull request closed without merging**
