### PR TITLE
jquery-timepicker

### PR DESCRIPTION
**Pull request by gregegan**
https://www.npmjs.com/package/jquery-timepicker

### CODE REVIEW

**Comment by marudor** [comment]
Just like your other PRs - could you fix the names?

**Comment by thejameskyle** [comment]
Yup the two files you should have are these:

```
/jquery-timepicker_v1.x.x/flow_>=v0.30.x/jquery-timepicker_v1.x.x.js.flow
/jquery-timepicker_v1.x.x/test_jquery-timepicker_v1.x.x.js.flow
```

The second is for adding tests to have a sanity check.

**Comment by gregegan** [comment]
Updated, lets see if tests pass

**Comment by marudor** [comment]
This hasn't been updated for quite a while and I can't add commits to the PR.
If this is still relevant please submit a new PR.

**Comment by Paxa** [comment]
@marudor Just need to rename files to get it merged?

**Pull request closed without merging**
