### PR TITLE
Angular 1.x

### PR DESCRIPTION
**Pull request by LoganBarnett**
This is a start on #361.

These are some types I've put together as a result of working with Angular 1.4.7. Generally Angular's types seem fairly grounded but I've yet to test them against other minor versions. There are definitely some gaps. Some of them are even in the declared types.

Also if someone has a better suggestion for how to define Angular's dependency injection, that would be awesome. The current pattern is an Array with strings (arg names) and a function as a last element whose arg count matches the number of strings. I'd be super happy for just something that declared the last element needs to be a function.

### CODE REVIEW

**Comment by bgergen** [comment]
Any progress being made on this? It would be awesome to be able to use Flow with Angular 1.x!

**Comment by LoganBarnett** [comment]
@bgergen It should be more or less usable. There will be some gaps, but you won't be starting from zero :)

**Comment by steida** [comment]
It breaks stuff. 

Found 38 dependencies in package.json. Searching for libdefs...
• rebasing flow-typed cache...done.
UNCAUGHT ERROR: Error: npm/angular_v1.4.7/flow_v0.37.x: Malformed flow-version directory name! Expected the name to be formatted as 'flow_all' or 'flow_-?v<VERSION>' or 'flow_v<VERSION>-?' or 'flow_v<VERSION>-v<VERSION>' (for a range).
    at validationError (/Users/steida/.nvm/versions/node/v7.8.0/lib/node_modules/flow-typed/dist/lib/libDefs.js:804:11)
    at invalidDirectoryName (/Users/steida/.nvm/versions/node/v7.8.0/lib/node_modules/flow-typed/dist/lib/libDefs.js:484:5)
    at parsePkgFlowDirVersion (/Users/steida/.nvm/versions/node/v7.8.0/lib/node_modules/flow-typed/dist/lib/libDefs.js:551:5)
    at /Users/steida/.nvm/versions/node/v7.8.0/lib/node_modules/flow-typed/dist/lib/libDefs.js:604:46
    at Array.forEach (native)
    at parseLibDefsFromPkgDir$ (/Users/steida/.nvm/versions/node/v7.8.0/lib/node_modules/flow-typed/dist/lib/libDefs.js:588:23)
    at tryCatch (/Users/steida/.nvm

**Comment by LoganBarnett** [comment]
@steida sorry you're having trouble. I've synced with master and run the tests against the angular suite and it seems to be working fine. My node version I'm using is 7.7.4 and the commit is 4477b0062bd7ec4bbbdb87017390c384a739ffaf, if that's any help triangulating what's going on for you. For what it's worth, the error seems to be complaining about the flow version, but the flow version it shows satisfies its requirements.

**Pull request merged**
