### PR TITLE
Ramda: Add definition for sortWith

### PR DESCRIPTION
**Pull request by forticulous**

### CODE REVIEW

**Comment by forticulous** [comment]
Hmm, those travis errors don't look like they're related to anything I did

**Comment by functionalStoic** [comment]
@forticulous I had what seems to be a similar failure on ramda related PR
https://github.com/flowtype/flow-typed/pull/1772

Let me know if you figure anything out with yours. Thanks!

**Comment by forticulous** [comment]
@GAntoine @functionalStoic 

It looks like there were some type issues with the existing code and flow > 0.62.0. I added a new folder for flow_v0.62.0- and limited the old folder to 0.49.0-0.61.0. There were two issues in the new folder, one I added a TODO to fix it, and the other I fixed by moving an // $ExpectError line

**Comment by GAntoine** [comment]
Considering the current broken state of ramda, this seems like the best fix. Let me give it a quick review, and I'll merge it in.

**Pull request merged**
