### PR TITLE
Add firestore to firebase. Fixes gh-1657

### PR DESCRIPTION
**Pull request by paularmstrong**
**Problem:** Firebase is missing Firestore definitions (gh-1657).

**Solution:** Add them. Followed the official [Firestore reference documentation](https://firebase.google.com/docs/reference/js/firebase.firestore)

### CODE REVIEW

**Comment by lohmander** [comment]
Is anyone working on getting this merged?

**Comment by paularmstrong** [comment]
@lohmander I'll get back to it when I have time, but am currently stuck on some other things. Feel free to take it over if you need it now.

**Comment by paularmstrong** [comment]
Updated and fixed tests.

**Comment by AndrewSouthpaw** [comment]
Thanks @paularmstrong for contributing!

**Pull request merged**
