### PR TITLE
jquery

### PR DESCRIPTION
**Pull request by marudor**

### CODE REVIEW

**Comment by jeffmo** [comment]
This one's a doozy! Probably warrants a good audit, but we shouldn't spin forever here since this one is probably pretty commonly requested.

Will come back to this later

**Comment by emily-e** [comment]
the JQuery class seems to be missing the .remove() method: https://api.jquery.com/remove/

**Comment by emily-e** [comment]
Also, all the fields of the JQueryAjaxSettings should be optional so the two AJAX methods on lines 642 and 649 work(I got this to work locally using $Shape: `ajax(settings: $Shape<JQueryAjaxSettings>): JQueryXHR;` ( http://api.jquery.com/jquery.ajax/ - "settings -Type: PlainObject - A set of key/value pairs that configure the Ajax request. All settings are optional.")

**Comment by unhammer** [comment]
thanks @emily-e! I use this currently:
[shape.diff.txt](https://github.com/flowtype/flow-typed/files/489256/shape.diff.txt)
but of course it loses some info on the functions (I couldn't figure out where to put the `?` – https://flowtype.org/docs/objects.html#optional-properties only talks about non-function fields)

**Comment by IanVS** [comment]
I see that this issue is closed.  Is it no longer planned to bring `jquery` into `flow-typed`?

**Comment by marudor** [comment]
@IanVS it is.
But this was a conversion from typescript and very immature.

**Pull request closed without merging**
