### PR TITLE
Add react router v4

### PR DESCRIPTION
**Pull request by aaronjensen**
Now that the API is meant to be stable, here are some flowtype definitions for v4.

I'm not sure what the policy on betas are, but these should be good to go.

### CODE REVIEW

**Comment by aaronjensen** [comment]
@ryanflorence @mjackson if you could review these I'd very much appreciate it. Thanks!

**Comment by aaronjensen** [comment]
Is there a way to rexport types from another module in flow-typed? Or is copy/paste as I did the way to go?

**Comment by mjackson** [comment]
LGTM, @aaronjensen. The only thing I'd suggest you keep an eye on is https://github.com/ReactTraining/react-router/issues/4424

We're getting some pushback from users who want all the router props in a `router` prop instead of spread out like they currently are. That will probably change the work you're doing here.

**Comment by ryyppy** [comment]
@aaronjensen it's up to you.. either copy paste it, or do a `import type {...} from 'other-module'` and hope user have the libdef for that module installed (the missing libdef error messages will probably lead the way :-) )

Ready to merge?

**Comment by aaronjensen** [comment]
@ryyppy ok, thanks. Yes, let's merge, thanks.

Unfortunately, `import type` breaks tests in this repo as far as I can tell.

**Comment by ryyppy** [comment]
cool thanks !

**Comment by rhlrjv** [comment]
@aaronjensen The dir structure seems to be off for this change. I am seeing this error on running `flow-typed install`.

```
UNCAUGHT ERROR: Error: npm/react-router-dom_v4.x.x/flow_v0.38-: Malformed flow-version directory name! Expected the name to be formatted as 'flow_all' or 'flow_-?v<VERSION>' or 'flow_v<VERSION>-?' or 'flow_v<VERSION>-v<VERSION>' (for a range).
```

Just wanted to let you guys know! 👍

**Comment by aaronjensen** [comment]
Oops, thanks @rhlrjv. Looks like @marudor already fixed it, thanks!

**Comment by ryyppy** [comment]
Huh? Why did our CI server let this through?

**Pull request merged**
