### PR TITLE
draft for any check

### PR DESCRIPTION
**Pull request by marudor**
To address https://github.com/flowtype/flow-typed/issues/49
very basic check. It uses flow dump-types to check all types and searches for the "any" string.
Probably error prune. But the dump-type command does not dump each type. Arrow functions are one type, even with paramter.
So a arrow function with any type would not get catched if I do an exact match for any.
Anyone got an idea how to get better accuracy?

### CODE REVIEW

**Comment by jeffmo** [comment]
Woohoo! Thanks for tackling this

So on using `dump-types`: There's a good chance this could be a bit noisy since there are places where `any` can creep in even when the user didn't explicitly state them (i.e. returning a type from something in flow's built-in libs that uses one of the `any`-types).

Instead, it would be a little more direct to just use `flow ast` to look for references to annotations of `any`, `Object`, `Function`, etc. `flow ast` should go all the way back to 0.13 -- so should be available in [all versions of Flow that we support here](https://github.com/flowtype/flow-typed/blob/master/npm/src/commands/runTests.js#L93-L94).

**Comment by marudor** [comment]
Now obsolete - gonna do it with a eslint plugin.

**Comment by jeffmo** [comment]
Heya -- so just to color some thoughts before you spend too much time I wanted to toss out the consideration that an eslint plugin might be a little noisy?

Specifically: we probably want to tell the user once somewhere that anys aren't ideal and then let them decide if they want to ignore the note -- since sometimes any is unavoidable. Do you have something in mind with lint that would make this doable?

**Comment by marudor** [comment]
yes - count any in general, not per line base.
Use of /* eslint flow-typed/any: [2, x] */ to set the number of allowed any

**Comment by jeffmo** [comment]
Cool, glad to hear you're already on top of it then :)
Looking forward to what you come up with!

**Pull request closed without merging**
