### PR TITLE
feat(formik): add Props generic to add missing props on FormikActions

### PR DESCRIPTION
**Pull request by sibelius**
we can access component Props on handleSubmit thorough FormikActions

### CODE REVIEW

**Comment by GAntoine** [comment]
Seems one of the specs is failing, and expecting 2 arguments instead of just 1.

**Comment by sibelius** [comment]
what is the right way to run only `formik` tests?

it is not easy to find this info on the docs

**Comment by GAntoine** [comment]
`flow-typed run-tests formik`

**Comment by sibelius** [comment]
any way to run only against latest flow version?

**Comment by JCMais** [comment]
I've incorporated those changes on the other PR I've opened https://github.com/flowtype/flow-typed/pull/2262

**Comment by sibelius** [comment]
@GAntoine check this instead https://github.com/flowtype/flow-typed/pull/2262

tks

**Pull request closed without merging**
