### PR TITLE
Clarify that raw React types can be used in libdefs.

### LINKED ISSUE #1795: Unexpected `any`-typing of imports
It seems that many possible `import` and `import type` statements in libdefs can fail silently and end up typing their imports as `any`. Some of these are widely using in existing libdefs.

For instance, `import * as React from 'react';` results in `React` and all of its properties being `any`-typed. Apparently you have to use `React$ComponentType` etc., but I can't find any docs that clarify this. The `import * as React from 'react';` pattern is used extensively in many existing libdefs.

`import type` statements will fail without `declare module` blocks, but outside of those blocks they will also result in `any` types.

`import` statement (not `import type`) are only allowed outside `declare module` blocks, and seem to be guaranteed to result in an `any` type.

### PR DESCRIPTION
**Pull request by AndrewSouthpaw**
Closes #1795, #1954.

### CODE REVIEW

**Comment by saadq** [comment]
Doing `import type` works inside the `module` (as long as it is a built-in type) though right? For example doing stuff like

```js
declare module 'other-module' {
  import type { Node } from 'react';
  import type { Server } from 'http';

  declare var server: Server;
  declare var node: Node;
}
```

Should that be mentioned or should it not be to avoid complexity? 

As a side note it might be worth putting [this cheatsheet](https://www.saltycrane.com/flow-type-cheat-sheet/latest/) somewhere in the `CONTRIBUTING.md` so people know which internal types they can use.

**Comment by AndrewSouthpaw** [comment]
Catch up on #1857 before continuing, in case you haven't. 

> Unfortunately flow-typed does not currently support the second approach as it can't depend on other libdefs during the tests. Other problem is nasty dependencies between library definitions which might become very hard to maintain.

As I interpreted this, it doesn't work full stop. Admittedly, I didn't test it. Have you found otherwise?

**Comment by saadq** [comment]
Yeah, I have done so in some of the definitions I've submitted. Just double checked:

screen shot 2018-03-13 at 2 35 47 pm

screen shot 2018-03-13 at 2 35 49 pm

**Comment by AndrewSouthpaw** [comment]
Ah, good to know.

Well, based on the conversation in #1857, the current ruling is to not encourage dependencies between libdefs, because that could get gnarly very, very quickly. I propose we move forward with this PR, continue the conversation there, and update if needed?

**Comment by saadq** [comment]
Sounds good 👍

**Comment by AndrewSouthpaw** [comment]
Can I get a formal 👍 from @villesau or @GAntoine?

**Comment by villesau** [comment]
It's actually possible to import types which Flow has baked in, like everything from Node and React.

**Comment by zaynv** [comment]
@villesau I think that's what was being discussed above your comment.

**Pull request merged**
