### PR TITLE
[react-redux] Add ability to use MDP Object with mergeProps

### LINKED ISSUE #2222: react-redux: Using mergeProps with Object-type mapDispatchToProps
As far as I understand, https://github.com/flowtype/flow-typed/blob/master/definitions/npm/react-redux_v5.x.x/flow_v0.62.0-/react-redux_v5.x.x.js does not allow to use `mergeProps` with `mapDispatchToProps` defined as Object. Is it intended?

I receive the following errors:

```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/accounts/utils/withCompanyAccount.js:87:16

Cannot call connect because:
 • Either a callable signature is missing in object literal [1] but exists in MapDispatchToProps [2].
 • Or a callable signature is missing in object literal [1] but exists in MapDispatchToProps [3].

     src/withAccount.js
 [1]  57│ const mapDispatchToProps = {
      58│   onPersistAccount: accountsActions.persistAccount,
      59│   onRequestProject: projectsActions.requestMaybeInactiveProject,
      60│   onRequestExchange: exchangeActions.requestMaybeInactiveExchange,
      61│   onPersistProject: projectsActions.persistProject,
      62│   onPersistExchange: exchangeActions.persistExchange
      63│ };
        :
      84│   );
      85│ }
      86│
      87│ export default connect(mapStateToProps, mapDispatchToProps, mergeProps);
      88│

     flow-typed/npm/react-redux_v5.x.x.js
 [2] 132│     mapDispatchToProps: ?MapDispatchToProps<A, DP, RDP>,
        :
 [3] 147│     mapDispatchToProps: ?MapDispatchToProps<A, DP, RDP>,



Found 1 error

Only showing the most relevant union/intersection branches.
To see all branches, re-run Flow with --show-all-branches

```

### PR DESCRIPTION
**Pull request by 102**
fixes #2222

### CODE REVIEW

**Comment by AndrewSouthpaw** [comment]
cc @villesau

**Comment by villesau** [comment]
@102 Thanks for doing a PR! Looks otherwise good, but some tests seems to fail. Also the new types requires some test coverage.

**Comment by 102** [comment]
@villesau thanks for the update, I was waiting for an approval of idea before fixing the problems with tests

**Comment by 102** [comment]
@villesau @AndrewSouthpaw 
I've encountered a problem: looks like some tests are failing since at least #1731. I've fixed the problem with `React.ElementConfig` (https://github.com/facebook/flow/issues/5592, looks like it just doesn't work before flow@0.63).

However, 17 errors of this shape are still here
```
 Warning: test_connect.js:255
   255: // $ExpectError
        ^^^^^^^^^^^^^^^ Error suppressing comment. Unused suppression
```
(they're thrown from test for previous versions, `react-redux_v5.x.x/flow_v0.54.x-v0.62.x`, which I haven't touched in this PR).

Could you give any advice?

**Comment by villesau** [comment]
@102 It's a glitch in the test suite. Unfortunately the system matches only the name, not the version so all the libdef versions for `react-redux` are tested, not just the one you are working on. Normally the previous failures are just ignored, so no need to worry about test failures with previous versions.

**Pull request merged**
