### PR TITLE
Use interface to reuse codes

### PR DESCRIPTION
**Pull request by yamadayuki**
#### Why

I use `interface` for `Route`'s methods and `Router`'s methods, and I can improve the complexity of the tweaking codes.

### CODE REVIEW

**Comment by yamadayuki** [comment]
@marudor Thanks!

**Comment by SyncroIT** [comment]
Uh, I've edited the file here: https://github.com/flowtype/flow-typed/pull/200/files#r71435172 but your code is surely better than mine :+1: 
Do I need to close my pull request?

**Comment by marudor** [comment]
@SyncroIT I've closed your PR and referenced this PR.
Thanks for your work though.

**Comment by SyncroIT** [comment]
@yamadayuki
Can I know why you declared 2 times the same interface? Is it must declared 2 times?

**Comment by yamadayuki** [comment]
@SyncroIT 
Hi! First, I apologize to you for my imcomplete response.
I declared two interfaces `RouteMethodType<T>` and `RouterMethodType<T>` as below,
```js
declare interface RouteMethodType<T> {
  (middleware: Middleware): T;
  (...middleware: Array<Middleware>): T;
  (path: string|RegExp, ...middleware: Array<Middleware>): T;
}
declare interface RouterMethodType<T> {
  (middleware: Middleware): T;
  (...middleware: Array<Middleware>): T;
  (path: string|RegExp, ...middleware: Array<Middleware>): T;
  (path: string, router: Router): T;
}
```

I think this declaration is not neat. It is a little lengthy.
I want to declare `RouterMethodType<T>` using `RouteMethodType<T>`, but my experience about flowtype is imperfect. So I declare two slightly different interfaces. If you know how to inherit interface declaration, I beg your teaching.

Thank you for your question!

**Comment by leonardfactory** [comment]
@yamadayuki I think you can use type unions in order to "extend" an interface, something like this:

```js
interface RouteMethodType<T> {
  ...
}

interface RouterExtensions<T> {
    (path: string, router: Router): T;
}

// RouterMethodType is going to have both signatures.
type RouterMethodType<T> = RouteMethodType<T> & RouterExtensions<T>;
```

I wrote a simple example on [tryflow](https://tryflow.org/?code=LyogQGZsb3cgKi8KaW50ZXJmYWNlIEZvbzxUPiB7CiAgICAocGFyYW06IHN0cmluZyk6IHZvaWQ7Cn0KCmludGVyZmFjZSBCYXI8VD4gewogICAgKHBhcmFtOiBzdHJpbmcsIGFub3RoZXI6IHN0cmluZyk6IHZvaWQ7Cn0KCnR5cGUgRm9vQmFyPFQ+ID0gRm9vPFQ+ICYgQmFyPFQ+OwoKbGV0IG8xOkZvb0JhcjxudW1iZXI+ID0gKGZyb206c3RyaW5nLCB0bzpzdHJpbmcpID0+IHt9OwpsZXQgbzI6Rm9vQmFyPG51bWJlcj4gPSAoZnJvbTpzdHJpbmcpID0+IHt9OwoKbzEoJ2EnLCAnYicpOwpvMignYycpOw==), and it seems to work correctly. Let me know if this solution sounds better to you!

**Comment by yamadayuki** [comment]
@leonardfactory 
Thank you for your advice 👍 
Your solution is nice! This can achieve the goal of declaration and reduce codes.
```diff
-  declare interface RouterMethodType<T> {
-    (middleware: Middleware): T;
-    (...middleware: Array<Middleware>): T;
-    (path: string|RegExp, ...middleware: Array<Middleware>): T;
+  declare interface RouterExtendsions<T> {
     (path: string, router: Router): T;
   }
+  declare type RouterMethodType<T> = RouteMethodType<T> & RouterExtendsions<T>;
```

express_use_interface

**Pull request merged**
