### PR TITLE
update puppeteer typedef and tests

### PR DESCRIPTION
**Pull request by infinityfarm**
@saadq This updates the typedef taking your comments into consideration and adds more extensive tests. Please let me know if you have any other comments/suggestions. cc @AndrewSouthpaw

### CODE REVIEW

**Comment by saadq** [comment]
Hey @infinityfarm, awesome work! So you mentioned in [this comment](https://github.com/flowtype/flow-typed/pull/2037#issuecomment-379282191) that you were having trouble extending the `EventEmitter` class, which I assume is why you created your own mock class. So as you probably noticed, you can only `import type` or `import typeof`, which only imports the type, so you can't use the type as a value. 

Instead, you will want to use Flow's private types/classes. Most of these are named like `module$Name`. in this case, you will want to extend `events$EventEmitter`.

Example:

```ts
declare module 'example' {
  declare class MyClass extends events$EventEmitter {

  }
}
```

There is a list of these Flow "private types" available [here](https://www.saltycrane.com/flow-type-cheat-sheet/latest/). The `events$EventEmitter` is in the [Node.js "private" types](https://www.saltycrane.com/flow-type-cheat-sheet/latest/#lib/node.js-private) section.

Other than that, everything looks really good!

**Comment by infinityfarm** [comment]
@saadq I've updated it to use the private type the best I could. I had to create an `OverridableEventEmitter` class that extends the built in `events$EventEmitter` because using the `events$EventEmitter` unchanged resulted in the following error message:
screen shot 2018-04-07 at 12 05 44 am
If there's a better way to fix that please advise.

Thanks

**Comment by saadq** [comment]
@infinityfarm Ah, yeah I remember having issues with the string literal vs string approach too... I had a StackOverflow post about it [here](https://stackoverflow.com/questions/49411515/limiting-the-type-of-eventname-in-a-class-that-extends-eventemitter-with-flow) that got answered.

The approach you did here looks fine to me too, I think this is ready for merging unless @GAntoine or anyone has any other comments.

**Comment by GAntoine** [comment]
No comments, changes look good to me. 👍

**Pull request merged**
