### PR TITLE
Support debug 2.x

### PR DESCRIPTION
**Pull request by thejameskyle**

### CODE REVIEW

**Comment by marudor** [comment]
Simple library, simple libdef, thanks for the work.

**Comment by valscion** [comment]
Please revert this @marudor, it broke all `flow-typed` installations as the flow version was specified incorrectly. Even the CI showed a failed build because of this.

**Comment by valscion** [comment]
Or better yet, @marudor if you could merge #173 after the CI is ready, that'd be great.

**Comment by marudor** [comment]
My bad :/
As travis failed anyways I simply missed the error.
I fixed travis though and once npm is back up all should be fine.

**Comment by valscion** [comment]
Thanks! :+1:

**Pull request merged**
