### PR TITLE
Fix lodash toPairs/toPairsIn/entries/entriesIn

### LINKED ISSUE #656: `_.toPairs` should not use nested array
https://github.com/flowtype/flow-typed/blob/master/definitions/npm/lodash_v4.x.x/flow_v0.38.x-/lodash_v4.x.x.js#L406

`NestedArray` assumes that both items are of the same type.

```js
_.toPair({foo: 3})
```

should work

### PR DESCRIPTION
**Pull request by ZhangYiJiang**
This fixes #656. 

`_.toPairs` takes an object and returns an array of key-value tuples ([docs](https://lodash.com/docs/4.17.4#toPairs)). 

The old libdef defined the return value as `NestedArray<T> = Array<Array<T>>`, which is too strict because an object can have non-string values (the key will always be string type). 

``` js 
var o = {
  a: 12, 
  b: 100,
};

// This fails, because Flow expects pairs to be [string][]
var pairs: [string, number][] = _.toPairs(o); // => [['a', 12], ['b', 100]]
```

### CODE REVIEW

**Comment by ZhangYiJiang** [comment]
@GAntoine Hmmm, I don't understand the Travis error. 

```
ERROR: lodash_v4.x.x/flow_v0.55.x-

 * lodash_v4.x.x/flow_v0.55.x- (flow-v0.61.0): Unexpected Flow errors(126):

   /bin/sh: 1: /home/travis/build/flowtype/flow-typed/cli/.flow-bins-cache/flow-v0.61.0: Permission denied

   

   null
```

It looks like the script failed with a permissions error? 

`flow-typed run-tests` runs fine locally: 

```
$ flow-typed run-tests lodash 
Running definition tests in /home/zhang/Documents/flow-typed/definitions/npm...

Fetching all Flow binaries...
Finished fetching Flow binaries.

Testing lodash_v4.x.x/flow_v0.28.x-v0.37.x (flow-v0.28.0)...
Testing lodash_v4.x.x/flow_v0.28.x-v0.37.x (flow-v0.29.0)...
[...]
Testing lodash_v4.x.x/flow_v0.55.x- (flow-v0.60.1)...
Testing lodash_v4.x.x/flow_v0.55.x- (flow-v0.61.0)...
 
All tests passed!
```

**Comment by GAntoine** [comment]
@ZhangYiJiang Yeah that's my bad, it's just been fixed on master. Could you pull the latest master, rebase this branch on it, and  see if that works? If not I'll take over in a new PR.

**Comment by ZhangYiJiang** [comment]
@GAntoine Hmmm, still failing with the same error after merging in master. Could you take a look? Thanks!

**Comment by GAntoine** [comment]
Closed in favour of #1634

**Pull request closed without merging**
