### PR TITLE
Support Inquirer 1.x & Through 2.x

### PR DESCRIPTION
**Pull request by thejameskyle**
Talked to @jeffmo about depending on types from other libraries and he advised me to just leave a todo for when lib def imports are supported.

### CODE REVIEW

**Comment by marudor** [comment]
libdefs look nice - File names are malformed though. (its v0.27 for instead of 0.27 for flow for instance)
Once its fixed and tests (for inquirer & through) pass I'm gonna merge.

**Comment by thejameskyle** [comment]
Fixed

**Comment by marudor** [comment]
Well - 19 Test Errors, guess you gotta work a bit on this :D

**Comment by marudor** [comment]
This hasn't been updated for quite a while and I can't add commits to the PR.
If this is still relevant please submit a new PR.

**Pull request closed without merging**
