### PR TITLE
Implement libdefs for Marked

### PR DESCRIPTION
**Pull request by Kriegslustig**
This PR add libdefs for [Marked](https://www.npmjs.com/package/marked) NPM package.

### CODE REVIEW

**Comment by Kriegslustig** [comment]
The latest build fail because of a network error. Could someone with write access trigger another build?

**Comment by jeffmo** [comment]
Ok so travis ran and it's now breaking because I just landed https://github.com/flowtype/flow-typed/pull/308.

We knew this would be a little painful, but luckily the fix is easy:

Would you mind just renaming the flow dir from "flow_>=v0.28.x" to "flow_v0.28.x-"? This is our new (windows-compatible) range syntax for flow directories.

**Comment by Kriegslustig** [comment]
Alright, thanks pushed a new version of it. Should have done it in another commit tough, sorry.

**Comment by jeffmo** [comment]
awesome!

**Pull request merged**
