### PR TITLE
Add tinycolor2

### PR DESCRIPTION
**Pull request by lifeiscontent**
@marudor ping

### CODE REVIEW

**Comment by marudor** [comment]
Could you add a few more tests?

**Comment by lifeiscontent** [comment]
@marudor what would be considered "good tests" for libdefs? Can you give me some basic examples?

**Comment by marudor** [comment]
For somthing like this just very basic tests should be enough
I made libdefs for another color library a year ago. 
https://github.com/flowtype/flow-typed/blob/master/definitions/npm/color_v0.7.x/test_color_v0.7.x.js

**Comment by lifeiscontent** [comment]
@marudor can you tell me why I'm getting an error in this test?

**Pull request closed without merging**
